/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 6.0.4
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QLCDNumber>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralwidget;
    QPushButton *NorthButton;
    QPushButton *EastButton;
    QPushButton *WestButton;
    QPushButton *SouthButton;
    QLabel *dir_label;
    QPushButton *MapButton;
    QLabel *imgLabel;
    QComboBox *TeleportBox;
    QPushButton *TeleportButton;
    QPushButton *TakeButton;
    QComboBox *ItemBox;
    QLCDNumber *inventorycounter;
    QLabel *inventory_label;
    QComboBox *InventoryBox;
    QPushButton *DropButton;
    QLineEdit *wordleEdit;
    QMenuBar *menubar;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(1272, 720);
        QPalette palette;
        QBrush brush(QColor(0, 0, 0, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush1(QColor(253, 253, 150, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Button, brush1);
        QBrush brush2(QColor(255, 255, 255, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Light, brush2);
        QBrush brush3(QColor(254, 254, 202, 255));
        brush3.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        QBrush brush4(QColor(126, 126, 75, 255));
        brush4.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Dark, brush4);
        QBrush brush5(QColor(169, 169, 100, 255));
        brush5.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Active, QPalette::Text, brush);
        palette.setBrush(QPalette::Active, QPalette::BrightText, brush2);
        palette.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Active, QPalette::Base, brush2);
        palette.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette.setBrush(QPalette::Active, QPalette::AlternateBase, brush3);
        QBrush brush6(QColor(255, 255, 220, 255));
        brush6.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::ToolTipBase, brush6);
        palette.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        QBrush brush7(QColor(239, 239, 239, 255));
        brush7.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Inactive, QPalette::Button, brush7);
        palette.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        QBrush brush8(QColor(202, 202, 202, 255));
        brush8.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Inactive, QPalette::Midlight, brush8);
        QBrush brush9(QColor(159, 159, 159, 255));
        brush9.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Inactive, QPalette::Dark, brush9);
        QBrush brush10(QColor(184, 184, 184, 255));
        brush10.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Inactive, QPalette::Mid, brush10);
        palette.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette.setBrush(QPalette::Inactive, QPalette::BrightText, brush2);
        palette.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Base, brush2);
        palette.setBrush(QPalette::Inactive, QPalette::Window, brush7);
        QBrush brush11(QColor(118, 118, 118, 255));
        brush11.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Inactive, QPalette::Shadow, brush11);
        QBrush brush12(QColor(247, 247, 247, 255));
        brush12.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush12);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush6);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::BrightText, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        QBrush brush13(QColor(177, 177, 177, 255));
        brush13.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Disabled, QPalette::Shadow, brush13);
        palette.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush12);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush6);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        MainWindow->setPalette(palette);
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        NorthButton = new QPushButton(centralwidget);
        NorthButton->setObjectName(QString::fromUtf8("NorthButton"));
        NorthButton->setGeometry(QRect(880, 30, 131, 61));
        QPalette palette1;
        palette1.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush14(QColor(237, 212, 0, 255));
        brush14.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Button, brush14);
        QBrush brush15(QColor(255, 239, 100, 255));
        brush15.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Light, brush15);
        QBrush brush16(QColor(246, 225, 50, 255));
        brush16.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Midlight, brush16);
        QBrush brush17(QColor(118, 106, 0, 255));
        brush17.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Dark, brush17);
        QBrush brush18(QColor(158, 141, 0, 255));
        brush18.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Mid, brush18);
        palette1.setBrush(QPalette::Active, QPalette::Text, brush);
        palette1.setBrush(QPalette::Active, QPalette::BrightText, brush2);
        palette1.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette1.setBrush(QPalette::Active, QPalette::Base, brush2);
        palette1.setBrush(QPalette::Active, QPalette::Window, brush14);
        palette1.setBrush(QPalette::Active, QPalette::Shadow, brush);
        QBrush brush19(QColor(246, 233, 127, 255));
        brush19.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::AlternateBase, brush19);
        palette1.setBrush(QPalette::Active, QPalette::ToolTipBase, brush6);
        palette1.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Button, brush7);
        palette1.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette1.setBrush(QPalette::Inactive, QPalette::Midlight, brush8);
        palette1.setBrush(QPalette::Inactive, QPalette::Dark, brush9);
        palette1.setBrush(QPalette::Inactive, QPalette::Mid, brush10);
        palette1.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::BrightText, brush2);
        palette1.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Base, brush2);
        palette1.setBrush(QPalette::Inactive, QPalette::Window, brush7);
        palette1.setBrush(QPalette::Inactive, QPalette::Shadow, brush11);
        palette1.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush12);
        palette1.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush6);
        palette1.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::WindowText, brush17);
        palette1.setBrush(QPalette::Disabled, QPalette::Button, brush14);
        palette1.setBrush(QPalette::Disabled, QPalette::Light, brush15);
        palette1.setBrush(QPalette::Disabled, QPalette::Midlight, brush16);
        palette1.setBrush(QPalette::Disabled, QPalette::Dark, brush17);
        palette1.setBrush(QPalette::Disabled, QPalette::Mid, brush18);
        palette1.setBrush(QPalette::Disabled, QPalette::Text, brush17);
        palette1.setBrush(QPalette::Disabled, QPalette::BrightText, brush2);
        palette1.setBrush(QPalette::Disabled, QPalette::ButtonText, brush17);
        palette1.setBrush(QPalette::Disabled, QPalette::Base, brush14);
        palette1.setBrush(QPalette::Disabled, QPalette::Window, brush14);
        palette1.setBrush(QPalette::Disabled, QPalette::Shadow, brush13);
        palette1.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush12);
        palette1.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush6);
        palette1.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        NorthButton->setPalette(palette1);
        QFont font;
        font.setPointSize(15);
        font.setBold(true);
        font.setItalic(false);
        font.setKerning(true);
        NorthButton->setFont(font);
        EastButton = new QPushButton(centralwidget);
        EastButton->setObjectName(QString::fromUtf8("EastButton"));
        EastButton->setGeometry(QRect(1010, 140, 131, 61));
        QPalette palette2;
        palette2.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush20(QColor(204, 0, 0, 255));
        brush20.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::Button, brush20);
        QBrush brush21(QColor(255, 51, 51, 255));
        brush21.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::Light, brush21);
        QBrush brush22(QColor(229, 25, 25, 255));
        brush22.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::Midlight, brush22);
        QBrush brush23(QColor(102, 0, 0, 255));
        brush23.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::Dark, brush23);
        QBrush brush24(QColor(136, 0, 0, 255));
        brush24.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::Mid, brush24);
        palette2.setBrush(QPalette::Active, QPalette::Text, brush);
        palette2.setBrush(QPalette::Active, QPalette::BrightText, brush2);
        palette2.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette2.setBrush(QPalette::Active, QPalette::Base, brush2);
        palette2.setBrush(QPalette::Active, QPalette::Window, brush20);
        palette2.setBrush(QPalette::Active, QPalette::Shadow, brush);
        QBrush brush25(QColor(229, 127, 127, 255));
        brush25.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::AlternateBase, brush25);
        palette2.setBrush(QPalette::Active, QPalette::ToolTipBase, brush6);
        palette2.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Button, brush7);
        palette2.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette2.setBrush(QPalette::Inactive, QPalette::Midlight, brush8);
        palette2.setBrush(QPalette::Inactive, QPalette::Dark, brush9);
        palette2.setBrush(QPalette::Inactive, QPalette::Mid, brush10);
        palette2.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::BrightText, brush2);
        palette2.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Base, brush2);
        palette2.setBrush(QPalette::Inactive, QPalette::Window, brush7);
        palette2.setBrush(QPalette::Inactive, QPalette::Shadow, brush11);
        palette2.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush12);
        palette2.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::WindowText, brush23);
        palette2.setBrush(QPalette::Disabled, QPalette::Button, brush20);
        palette2.setBrush(QPalette::Disabled, QPalette::Light, brush21);
        palette2.setBrush(QPalette::Disabled, QPalette::Midlight, brush22);
        palette2.setBrush(QPalette::Disabled, QPalette::Dark, brush23);
        palette2.setBrush(QPalette::Disabled, QPalette::Mid, brush24);
        palette2.setBrush(QPalette::Disabled, QPalette::Text, brush23);
        palette2.setBrush(QPalette::Disabled, QPalette::BrightText, brush2);
        palette2.setBrush(QPalette::Disabled, QPalette::ButtonText, brush23);
        palette2.setBrush(QPalette::Disabled, QPalette::Base, brush20);
        palette2.setBrush(QPalette::Disabled, QPalette::Window, brush20);
        palette2.setBrush(QPalette::Disabled, QPalette::Shadow, brush13);
        palette2.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush12);
        palette2.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush6);
        palette2.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        EastButton->setPalette(palette2);
        QFont font1;
        font1.setPointSize(15);
        font1.setBold(true);
        EastButton->setFont(font1);
        WestButton = new QPushButton(centralwidget);
        WestButton->setObjectName(QString::fromUtf8("WestButton"));
        WestButton->setGeometry(QRect(750, 140, 131, 61));
        QPalette palette3;
        palette3.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush26(QColor(52, 101, 164, 255));
        brush26.setStyle(Qt::SolidPattern);
        palette3.setBrush(QPalette::Active, QPalette::Button, brush26);
        QBrush brush27(QColor(78, 151, 246, 255));
        brush27.setStyle(Qt::SolidPattern);
        palette3.setBrush(QPalette::Active, QPalette::Light, brush27);
        QBrush brush28(QColor(65, 126, 205, 255));
        brush28.setStyle(Qt::SolidPattern);
        palette3.setBrush(QPalette::Active, QPalette::Midlight, brush28);
        QBrush brush29(QColor(26, 50, 82, 255));
        brush29.setStyle(Qt::SolidPattern);
        palette3.setBrush(QPalette::Active, QPalette::Dark, brush29);
        QBrush brush30(QColor(35, 67, 109, 255));
        brush30.setStyle(Qt::SolidPattern);
        palette3.setBrush(QPalette::Active, QPalette::Mid, brush30);
        palette3.setBrush(QPalette::Active, QPalette::Text, brush);
        palette3.setBrush(QPalette::Active, QPalette::BrightText, brush2);
        palette3.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette3.setBrush(QPalette::Active, QPalette::Base, brush2);
        palette3.setBrush(QPalette::Active, QPalette::Window, brush26);
        palette3.setBrush(QPalette::Active, QPalette::Shadow, brush);
        QBrush brush31(QColor(153, 178, 209, 255));
        brush31.setStyle(Qt::SolidPattern);
        palette3.setBrush(QPalette::Active, QPalette::AlternateBase, brush31);
        palette3.setBrush(QPalette::Active, QPalette::ToolTipBase, brush6);
        palette3.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Button, brush7);
        palette3.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette3.setBrush(QPalette::Inactive, QPalette::Midlight, brush8);
        palette3.setBrush(QPalette::Inactive, QPalette::Dark, brush9);
        palette3.setBrush(QPalette::Inactive, QPalette::Mid, brush10);
        palette3.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::BrightText, brush2);
        palette3.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Base, brush2);
        palette3.setBrush(QPalette::Inactive, QPalette::Window, brush7);
        palette3.setBrush(QPalette::Inactive, QPalette::Shadow, brush11);
        palette3.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush12);
        palette3.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush6);
        palette3.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::WindowText, brush29);
        palette3.setBrush(QPalette::Disabled, QPalette::Button, brush26);
        palette3.setBrush(QPalette::Disabled, QPalette::Light, brush27);
        palette3.setBrush(QPalette::Disabled, QPalette::Midlight, brush28);
        palette3.setBrush(QPalette::Disabled, QPalette::Dark, brush29);
        palette3.setBrush(QPalette::Disabled, QPalette::Mid, brush30);
        palette3.setBrush(QPalette::Disabled, QPalette::Text, brush29);
        palette3.setBrush(QPalette::Disabled, QPalette::BrightText, brush2);
        palette3.setBrush(QPalette::Disabled, QPalette::ButtonText, brush29);
        palette3.setBrush(QPalette::Disabled, QPalette::Base, brush26);
        palette3.setBrush(QPalette::Disabled, QPalette::Window, brush26);
        palette3.setBrush(QPalette::Disabled, QPalette::Shadow, brush13);
        palette3.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush12);
        palette3.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush6);
        palette3.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        WestButton->setPalette(palette3);
        WestButton->setFont(font1);
        WestButton->setFlat(false);
        SouthButton = new QPushButton(centralwidget);
        SouthButton->setObjectName(QString::fromUtf8("SouthButton"));
        SouthButton->setGeometry(QRect(880, 250, 131, 61));
        QPalette palette4;
        palette4.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush32(QColor(78, 154, 6, 255));
        brush32.setStyle(Qt::SolidPattern);
        palette4.setBrush(QPalette::Active, QPalette::Button, brush32);
        QBrush brush33(QColor(117, 231, 9, 255));
        brush33.setStyle(Qt::SolidPattern);
        palette4.setBrush(QPalette::Active, QPalette::Light, brush33);
        QBrush brush34(QColor(97, 192, 7, 255));
        brush34.setStyle(Qt::SolidPattern);
        palette4.setBrush(QPalette::Active, QPalette::Midlight, brush34);
        QBrush brush35(QColor(39, 77, 3, 255));
        brush35.setStyle(Qt::SolidPattern);
        palette4.setBrush(QPalette::Active, QPalette::Dark, brush35);
        QBrush brush36(QColor(52, 103, 4, 255));
        brush36.setStyle(Qt::SolidPattern);
        palette4.setBrush(QPalette::Active, QPalette::Mid, brush36);
        palette4.setBrush(QPalette::Active, QPalette::Text, brush);
        palette4.setBrush(QPalette::Active, QPalette::BrightText, brush2);
        palette4.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette4.setBrush(QPalette::Active, QPalette::Base, brush2);
        palette4.setBrush(QPalette::Active, QPalette::Window, brush32);
        palette4.setBrush(QPalette::Active, QPalette::Shadow, brush);
        QBrush brush37(QColor(166, 204, 130, 255));
        brush37.setStyle(Qt::SolidPattern);
        palette4.setBrush(QPalette::Active, QPalette::AlternateBase, brush37);
        palette4.setBrush(QPalette::Active, QPalette::ToolTipBase, brush6);
        palette4.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Button, brush7);
        palette4.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette4.setBrush(QPalette::Inactive, QPalette::Midlight, brush8);
        palette4.setBrush(QPalette::Inactive, QPalette::Dark, brush9);
        palette4.setBrush(QPalette::Inactive, QPalette::Mid, brush10);
        palette4.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::BrightText, brush2);
        palette4.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Base, brush2);
        palette4.setBrush(QPalette::Inactive, QPalette::Window, brush7);
        palette4.setBrush(QPalette::Inactive, QPalette::Shadow, brush11);
        palette4.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush12);
        palette4.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush6);
        palette4.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::WindowText, brush35);
        palette4.setBrush(QPalette::Disabled, QPalette::Button, brush32);
        palette4.setBrush(QPalette::Disabled, QPalette::Light, brush33);
        palette4.setBrush(QPalette::Disabled, QPalette::Midlight, brush34);
        palette4.setBrush(QPalette::Disabled, QPalette::Dark, brush35);
        palette4.setBrush(QPalette::Disabled, QPalette::Mid, brush36);
        palette4.setBrush(QPalette::Disabled, QPalette::Text, brush35);
        palette4.setBrush(QPalette::Disabled, QPalette::BrightText, brush2);
        palette4.setBrush(QPalette::Disabled, QPalette::ButtonText, brush35);
        palette4.setBrush(QPalette::Disabled, QPalette::Base, brush32);
        palette4.setBrush(QPalette::Disabled, QPalette::Window, brush32);
        palette4.setBrush(QPalette::Disabled, QPalette::Shadow, brush13);
        palette4.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush12);
        palette4.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush6);
        palette4.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        SouthButton->setPalette(palette4);
        SouthButton->setFont(font1);
        dir_label = new QLabel(centralwidget);
        dir_label->setObjectName(QString::fromUtf8("dir_label"));
        dir_label->setGeometry(QRect(40, 420, 251, 161));
        QPalette palette5;
        palette5.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette5.setBrush(QPalette::Active, QPalette::Button, brush7);
        palette5.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette5.setBrush(QPalette::Active, QPalette::Midlight, brush8);
        palette5.setBrush(QPalette::Active, QPalette::Dark, brush9);
        palette5.setBrush(QPalette::Active, QPalette::Mid, brush10);
        palette5.setBrush(QPalette::Active, QPalette::Text, brush);
        palette5.setBrush(QPalette::Active, QPalette::BrightText, brush2);
        palette5.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette5.setBrush(QPalette::Active, QPalette::Base, brush2);
        palette5.setBrush(QPalette::Active, QPalette::Window, brush7);
        palette5.setBrush(QPalette::Active, QPalette::Shadow, brush11);
        QBrush brush38(QColor(48, 140, 198, 255));
        brush38.setStyle(Qt::SolidPattern);
        palette5.setBrush(QPalette::Active, QPalette::Highlight, brush38);
        palette5.setBrush(QPalette::Active, QPalette::HighlightedText, brush2);
        QBrush brush39(QColor(0, 0, 255, 255));
        brush39.setStyle(Qt::SolidPattern);
        palette5.setBrush(QPalette::Active, QPalette::Link, brush39);
        QBrush brush40(QColor(255, 0, 255, 255));
        brush40.setStyle(Qt::SolidPattern);
        palette5.setBrush(QPalette::Active, QPalette::LinkVisited, brush40);
        palette5.setBrush(QPalette::Active, QPalette::AlternateBase, brush12);
        palette5.setBrush(QPalette::Active, QPalette::NoRole, brush);
        palette5.setBrush(QPalette::Active, QPalette::ToolTipBase, brush6);
        palette5.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        QBrush brush41(QColor(0, 0, 0, 128));
        brush41.setStyle(Qt::SolidPattern);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette5.setBrush(QPalette::Active, QPalette::PlaceholderText, brush41);
#endif
        palette5.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::Button, brush7);
        palette5.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette5.setBrush(QPalette::Inactive, QPalette::Midlight, brush8);
        palette5.setBrush(QPalette::Inactive, QPalette::Dark, brush9);
        palette5.setBrush(QPalette::Inactive, QPalette::Mid, brush10);
        palette5.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::BrightText, brush2);
        palette5.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::Base, brush2);
        palette5.setBrush(QPalette::Inactive, QPalette::Window, brush7);
        palette5.setBrush(QPalette::Inactive, QPalette::Shadow, brush11);
        palette5.setBrush(QPalette::Inactive, QPalette::Highlight, brush38);
        palette5.setBrush(QPalette::Inactive, QPalette::HighlightedText, brush2);
        palette5.setBrush(QPalette::Inactive, QPalette::Link, brush39);
        palette5.setBrush(QPalette::Inactive, QPalette::LinkVisited, brush40);
        palette5.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush12);
        QBrush brush42(QColor(0, 0, 0, 255));
        brush42.setStyle(Qt::NoBrush);
        palette5.setBrush(QPalette::Inactive, QPalette::NoRole, brush42);
        palette5.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush6);
        palette5.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette5.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush41);
#endif
        QBrush brush43(QColor(190, 190, 190, 255));
        brush43.setStyle(Qt::SolidPattern);
        palette5.setBrush(QPalette::Disabled, QPalette::WindowText, brush43);
        palette5.setBrush(QPalette::Disabled, QPalette::Button, brush7);
        palette5.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette5.setBrush(QPalette::Disabled, QPalette::Midlight, brush8);
        palette5.setBrush(QPalette::Disabled, QPalette::Dark, brush43);
        palette5.setBrush(QPalette::Disabled, QPalette::Mid, brush10);
        palette5.setBrush(QPalette::Disabled, QPalette::Text, brush43);
        palette5.setBrush(QPalette::Disabled, QPalette::BrightText, brush2);
        palette5.setBrush(QPalette::Disabled, QPalette::ButtonText, brush43);
        palette5.setBrush(QPalette::Disabled, QPalette::Base, brush7);
        palette5.setBrush(QPalette::Disabled, QPalette::Window, brush7);
        palette5.setBrush(QPalette::Disabled, QPalette::Shadow, brush13);
        QBrush brush44(QColor(145, 145, 145, 255));
        brush44.setStyle(Qt::SolidPattern);
        palette5.setBrush(QPalette::Disabled, QPalette::Highlight, brush44);
        palette5.setBrush(QPalette::Disabled, QPalette::HighlightedText, brush2);
        palette5.setBrush(QPalette::Disabled, QPalette::Link, brush39);
        palette5.setBrush(QPalette::Disabled, QPalette::LinkVisited, brush40);
        palette5.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush12);
        QBrush brush45(QColor(0, 0, 0, 255));
        brush45.setStyle(Qt::NoBrush);
        palette5.setBrush(QPalette::Disabled, QPalette::NoRole, brush45);
        palette5.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush6);
        palette5.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette5.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush41);
#endif
        dir_label->setPalette(palette5);
        dir_label->setFrameShape(QFrame::Box);
        MapButton = new QPushButton(centralwidget);
        MapButton->setObjectName(QString::fromUtf8("MapButton"));
        MapButton->setGeometry(QRect(1040, 250, 131, 61));
        QPalette palette6;
        palette6.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush46(QColor(144, 214, 242, 255));
        brush46.setStyle(Qt::SolidPattern);
        palette6.setBrush(QPalette::Active, QPalette::Button, brush46);
        palette6.setBrush(QPalette::Active, QPalette::Light, brush2);
        QBrush brush47(QColor(199, 234, 248, 255));
        brush47.setStyle(Qt::SolidPattern);
        palette6.setBrush(QPalette::Active, QPalette::Midlight, brush47);
        QBrush brush48(QColor(72, 107, 121, 255));
        brush48.setStyle(Qt::SolidPattern);
        palette6.setBrush(QPalette::Active, QPalette::Dark, brush48);
        QBrush brush49(QColor(96, 143, 161, 255));
        brush49.setStyle(Qt::SolidPattern);
        palette6.setBrush(QPalette::Active, QPalette::Mid, brush49);
        palette6.setBrush(QPalette::Active, QPalette::Text, brush);
        palette6.setBrush(QPalette::Active, QPalette::BrightText, brush2);
        palette6.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette6.setBrush(QPalette::Active, QPalette::Base, brush2);
        palette6.setBrush(QPalette::Active, QPalette::Window, brush46);
        palette6.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette6.setBrush(QPalette::Active, QPalette::AlternateBase, brush47);
        palette6.setBrush(QPalette::Active, QPalette::ToolTipBase, brush6);
        palette6.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::Button, brush7);
        palette6.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette6.setBrush(QPalette::Inactive, QPalette::Midlight, brush8);
        palette6.setBrush(QPalette::Inactive, QPalette::Dark, brush9);
        palette6.setBrush(QPalette::Inactive, QPalette::Mid, brush10);
        palette6.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::BrightText, brush2);
        palette6.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::Base, brush2);
        palette6.setBrush(QPalette::Inactive, QPalette::Window, brush7);
        palette6.setBrush(QPalette::Inactive, QPalette::Shadow, brush11);
        palette6.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush12);
        palette6.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush6);
        palette6.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette6.setBrush(QPalette::Disabled, QPalette::WindowText, brush48);
        palette6.setBrush(QPalette::Disabled, QPalette::Button, brush46);
        palette6.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette6.setBrush(QPalette::Disabled, QPalette::Midlight, brush47);
        palette6.setBrush(QPalette::Disabled, QPalette::Dark, brush48);
        palette6.setBrush(QPalette::Disabled, QPalette::Mid, brush49);
        palette6.setBrush(QPalette::Disabled, QPalette::Text, brush48);
        palette6.setBrush(QPalette::Disabled, QPalette::BrightText, brush2);
        palette6.setBrush(QPalette::Disabled, QPalette::ButtonText, brush48);
        palette6.setBrush(QPalette::Disabled, QPalette::Base, brush46);
        palette6.setBrush(QPalette::Disabled, QPalette::Window, brush46);
        palette6.setBrush(QPalette::Disabled, QPalette::Shadow, brush13);
        palette6.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush12);
        palette6.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush6);
        palette6.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        MapButton->setPalette(palette6);
        QFont font2;
        MapButton->setFont(font2);
        imgLabel = new QLabel(centralwidget);
        imgLabel->setObjectName(QString::fromUtf8("imgLabel"));
        imgLabel->setGeometry(QRect(40, 10, 651, 361));
        QPalette palette7;
        palette7.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette7.setBrush(QPalette::Active, QPalette::Button, brush7);
        palette7.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette7.setBrush(QPalette::Active, QPalette::Midlight, brush8);
        palette7.setBrush(QPalette::Active, QPalette::Dark, brush9);
        palette7.setBrush(QPalette::Active, QPalette::Mid, brush10);
        palette7.setBrush(QPalette::Active, QPalette::Text, brush);
        palette7.setBrush(QPalette::Active, QPalette::BrightText, brush2);
        palette7.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette7.setBrush(QPalette::Active, QPalette::Base, brush2);
        palette7.setBrush(QPalette::Active, QPalette::Window, brush7);
        palette7.setBrush(QPalette::Active, QPalette::Shadow, brush11);
        palette7.setBrush(QPalette::Active, QPalette::Highlight, brush38);
        palette7.setBrush(QPalette::Active, QPalette::HighlightedText, brush2);
        palette7.setBrush(QPalette::Active, QPalette::Link, brush39);
        palette7.setBrush(QPalette::Active, QPalette::LinkVisited, brush40);
        palette7.setBrush(QPalette::Active, QPalette::AlternateBase, brush12);
        palette7.setBrush(QPalette::Active, QPalette::NoRole, brush);
        palette7.setBrush(QPalette::Active, QPalette::ToolTipBase, brush6);
        palette7.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette7.setBrush(QPalette::Active, QPalette::PlaceholderText, brush41);
#endif
        palette7.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::Button, brush7);
        palette7.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette7.setBrush(QPalette::Inactive, QPalette::Midlight, brush8);
        palette7.setBrush(QPalette::Inactive, QPalette::Dark, brush9);
        palette7.setBrush(QPalette::Inactive, QPalette::Mid, brush10);
        palette7.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::BrightText, brush2);
        palette7.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::Base, brush2);
        palette7.setBrush(QPalette::Inactive, QPalette::Window, brush7);
        palette7.setBrush(QPalette::Inactive, QPalette::Shadow, brush11);
        palette7.setBrush(QPalette::Inactive, QPalette::Highlight, brush38);
        palette7.setBrush(QPalette::Inactive, QPalette::HighlightedText, brush2);
        palette7.setBrush(QPalette::Inactive, QPalette::Link, brush39);
        palette7.setBrush(QPalette::Inactive, QPalette::LinkVisited, brush40);
        palette7.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush12);
        QBrush brush50(QColor(0, 0, 0, 255));
        brush50.setStyle(Qt::NoBrush);
        palette7.setBrush(QPalette::Inactive, QPalette::NoRole, brush50);
        palette7.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush6);
        palette7.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette7.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush41);
#endif
        palette7.setBrush(QPalette::Disabled, QPalette::WindowText, brush43);
        palette7.setBrush(QPalette::Disabled, QPalette::Button, brush7);
        palette7.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette7.setBrush(QPalette::Disabled, QPalette::Midlight, brush8);
        palette7.setBrush(QPalette::Disabled, QPalette::Dark, brush43);
        palette7.setBrush(QPalette::Disabled, QPalette::Mid, brush10);
        palette7.setBrush(QPalette::Disabled, QPalette::Text, brush43);
        palette7.setBrush(QPalette::Disabled, QPalette::BrightText, brush2);
        palette7.setBrush(QPalette::Disabled, QPalette::ButtonText, brush43);
        palette7.setBrush(QPalette::Disabled, QPalette::Base, brush7);
        palette7.setBrush(QPalette::Disabled, QPalette::Window, brush7);
        palette7.setBrush(QPalette::Disabled, QPalette::Shadow, brush13);
        palette7.setBrush(QPalette::Disabled, QPalette::Highlight, brush44);
        palette7.setBrush(QPalette::Disabled, QPalette::HighlightedText, brush2);
        palette7.setBrush(QPalette::Disabled, QPalette::Link, brush39);
        palette7.setBrush(QPalette::Disabled, QPalette::LinkVisited, brush40);
        palette7.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush12);
        QBrush brush51(QColor(0, 0, 0, 255));
        brush51.setStyle(Qt::NoBrush);
        palette7.setBrush(QPalette::Disabled, QPalette::NoRole, brush51);
        palette7.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush6);
        palette7.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette7.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush41);
#endif
        imgLabel->setPalette(palette7);
        imgLabel->setFrameShape(QFrame::Panel);
        imgLabel->setFrameShadow(QFrame::Raised);
        imgLabel->setLineWidth(6);
        TeleportBox = new QComboBox(centralwidget);
        TeleportBox->setObjectName(QString::fromUtf8("TeleportBox"));
        TeleportBox->setGeometry(QRect(720, 470, 131, 25));
        QPalette palette8;
        palette8.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush52(QColor(114, 159, 207, 255));
        brush52.setStyle(Qt::SolidPattern);
        palette8.setBrush(QPalette::Active, QPalette::Button, brush52);
        QBrush brush53(QColor(196, 225, 255, 255));
        brush53.setStyle(Qt::SolidPattern);
        palette8.setBrush(QPalette::Active, QPalette::Light, brush53);
        QBrush brush54(QColor(155, 192, 231, 255));
        brush54.setStyle(Qt::SolidPattern);
        palette8.setBrush(QPalette::Active, QPalette::Midlight, brush54);
        QBrush brush55(QColor(57, 79, 103, 255));
        brush55.setStyle(Qt::SolidPattern);
        palette8.setBrush(QPalette::Active, QPalette::Dark, brush55);
        QBrush brush56(QColor(76, 106, 138, 255));
        brush56.setStyle(Qt::SolidPattern);
        palette8.setBrush(QPalette::Active, QPalette::Mid, brush56);
        palette8.setBrush(QPalette::Active, QPalette::Text, brush);
        palette8.setBrush(QPalette::Active, QPalette::BrightText, brush2);
        palette8.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette8.setBrush(QPalette::Active, QPalette::Base, brush2);
        palette8.setBrush(QPalette::Active, QPalette::Window, brush52);
        palette8.setBrush(QPalette::Active, QPalette::Shadow, brush);
        QBrush brush57(QColor(184, 207, 231, 255));
        brush57.setStyle(Qt::SolidPattern);
        palette8.setBrush(QPalette::Active, QPalette::AlternateBase, brush57);
        palette8.setBrush(QPalette::Active, QPalette::ToolTipBase, brush6);
        palette8.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::Button, brush7);
        palette8.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette8.setBrush(QPalette::Inactive, QPalette::Midlight, brush8);
        palette8.setBrush(QPalette::Inactive, QPalette::Dark, brush9);
        palette8.setBrush(QPalette::Inactive, QPalette::Mid, brush10);
        palette8.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::BrightText, brush2);
        palette8.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::Base, brush2);
        palette8.setBrush(QPalette::Inactive, QPalette::Window, brush7);
        palette8.setBrush(QPalette::Inactive, QPalette::Shadow, brush11);
        palette8.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush12);
        palette8.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush6);
        palette8.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette8.setBrush(QPalette::Disabled, QPalette::WindowText, brush55);
        palette8.setBrush(QPalette::Disabled, QPalette::Button, brush52);
        palette8.setBrush(QPalette::Disabled, QPalette::Light, brush53);
        palette8.setBrush(QPalette::Disabled, QPalette::Midlight, brush54);
        palette8.setBrush(QPalette::Disabled, QPalette::Dark, brush55);
        palette8.setBrush(QPalette::Disabled, QPalette::Mid, brush56);
        palette8.setBrush(QPalette::Disabled, QPalette::Text, brush55);
        palette8.setBrush(QPalette::Disabled, QPalette::BrightText, brush2);
        palette8.setBrush(QPalette::Disabled, QPalette::ButtonText, brush55);
        palette8.setBrush(QPalette::Disabled, QPalette::Base, brush52);
        palette8.setBrush(QPalette::Disabled, QPalette::Window, brush52);
        palette8.setBrush(QPalette::Disabled, QPalette::Shadow, brush13);
        palette8.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush12);
        palette8.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush6);
        palette8.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        TeleportBox->setPalette(palette8);
        TeleportButton = new QPushButton(centralwidget);
        TeleportButton->setObjectName(QString::fromUtf8("TeleportButton"));
        TeleportButton->setGeometry(QRect(720, 400, 131, 61));
        QPalette palette9;
        palette9.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette9.setBrush(QPalette::Active, QPalette::Button, brush46);
        palette9.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette9.setBrush(QPalette::Active, QPalette::Midlight, brush47);
        palette9.setBrush(QPalette::Active, QPalette::Dark, brush48);
        palette9.setBrush(QPalette::Active, QPalette::Mid, brush49);
        palette9.setBrush(QPalette::Active, QPalette::Text, brush);
        palette9.setBrush(QPalette::Active, QPalette::BrightText, brush2);
        palette9.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette9.setBrush(QPalette::Active, QPalette::Base, brush2);
        palette9.setBrush(QPalette::Active, QPalette::Window, brush46);
        palette9.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette9.setBrush(QPalette::Active, QPalette::AlternateBase, brush47);
        palette9.setBrush(QPalette::Active, QPalette::ToolTipBase, brush6);
        palette9.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::Button, brush7);
        palette9.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette9.setBrush(QPalette::Inactive, QPalette::Midlight, brush8);
        palette9.setBrush(QPalette::Inactive, QPalette::Dark, brush9);
        palette9.setBrush(QPalette::Inactive, QPalette::Mid, brush10);
        palette9.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::BrightText, brush2);
        palette9.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::Base, brush2);
        palette9.setBrush(QPalette::Inactive, QPalette::Window, brush7);
        palette9.setBrush(QPalette::Inactive, QPalette::Shadow, brush11);
        palette9.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush12);
        palette9.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush6);
        palette9.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette9.setBrush(QPalette::Disabled, QPalette::WindowText, brush48);
        palette9.setBrush(QPalette::Disabled, QPalette::Button, brush46);
        palette9.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette9.setBrush(QPalette::Disabled, QPalette::Midlight, brush47);
        palette9.setBrush(QPalette::Disabled, QPalette::Dark, brush48);
        palette9.setBrush(QPalette::Disabled, QPalette::Mid, brush49);
        palette9.setBrush(QPalette::Disabled, QPalette::Text, brush48);
        palette9.setBrush(QPalette::Disabled, QPalette::BrightText, brush2);
        palette9.setBrush(QPalette::Disabled, QPalette::ButtonText, brush48);
        palette9.setBrush(QPalette::Disabled, QPalette::Base, brush46);
        palette9.setBrush(QPalette::Disabled, QPalette::Window, brush46);
        palette9.setBrush(QPalette::Disabled, QPalette::Shadow, brush13);
        palette9.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush12);
        palette9.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush6);
        palette9.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        TeleportButton->setPalette(palette9);
        TeleportButton->setFont(font2);
        TakeButton = new QPushButton(centralwidget);
        TakeButton->setObjectName(QString::fromUtf8("TakeButton"));
        TakeButton->setGeometry(QRect(880, 400, 131, 61));
        QPalette palette10;
        palette10.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette10.setBrush(QPalette::Active, QPalette::Button, brush46);
        palette10.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette10.setBrush(QPalette::Active, QPalette::Midlight, brush47);
        palette10.setBrush(QPalette::Active, QPalette::Dark, brush48);
        palette10.setBrush(QPalette::Active, QPalette::Mid, brush49);
        palette10.setBrush(QPalette::Active, QPalette::Text, brush);
        palette10.setBrush(QPalette::Active, QPalette::BrightText, brush2);
        palette10.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette10.setBrush(QPalette::Active, QPalette::Base, brush2);
        palette10.setBrush(QPalette::Active, QPalette::Window, brush46);
        palette10.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette10.setBrush(QPalette::Active, QPalette::AlternateBase, brush47);
        palette10.setBrush(QPalette::Active, QPalette::ToolTipBase, brush6);
        palette10.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette10.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette10.setBrush(QPalette::Inactive, QPalette::Button, brush7);
        palette10.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette10.setBrush(QPalette::Inactive, QPalette::Midlight, brush8);
        palette10.setBrush(QPalette::Inactive, QPalette::Dark, brush9);
        palette10.setBrush(QPalette::Inactive, QPalette::Mid, brush10);
        palette10.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette10.setBrush(QPalette::Inactive, QPalette::BrightText, brush2);
        palette10.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette10.setBrush(QPalette::Inactive, QPalette::Base, brush2);
        palette10.setBrush(QPalette::Inactive, QPalette::Window, brush7);
        palette10.setBrush(QPalette::Inactive, QPalette::Shadow, brush11);
        palette10.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush12);
        palette10.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush6);
        palette10.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette10.setBrush(QPalette::Disabled, QPalette::WindowText, brush48);
        palette10.setBrush(QPalette::Disabled, QPalette::Button, brush46);
        palette10.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette10.setBrush(QPalette::Disabled, QPalette::Midlight, brush47);
        palette10.setBrush(QPalette::Disabled, QPalette::Dark, brush48);
        palette10.setBrush(QPalette::Disabled, QPalette::Mid, brush49);
        palette10.setBrush(QPalette::Disabled, QPalette::Text, brush48);
        palette10.setBrush(QPalette::Disabled, QPalette::BrightText, brush2);
        palette10.setBrush(QPalette::Disabled, QPalette::ButtonText, brush48);
        palette10.setBrush(QPalette::Disabled, QPalette::Base, brush46);
        palette10.setBrush(QPalette::Disabled, QPalette::Window, brush46);
        palette10.setBrush(QPalette::Disabled, QPalette::Shadow, brush13);
        palette10.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush12);
        palette10.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush6);
        palette10.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        TakeButton->setPalette(palette10);
        TakeButton->setFont(font2);
        ItemBox = new QComboBox(centralwidget);
        ItemBox->setObjectName(QString::fromUtf8("ItemBox"));
        ItemBox->setGeometry(QRect(880, 470, 131, 25));
        QPalette palette11;
        palette11.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette11.setBrush(QPalette::Active, QPalette::Button, brush52);
        palette11.setBrush(QPalette::Active, QPalette::Light, brush53);
        palette11.setBrush(QPalette::Active, QPalette::Midlight, brush54);
        palette11.setBrush(QPalette::Active, QPalette::Dark, brush55);
        palette11.setBrush(QPalette::Active, QPalette::Mid, brush56);
        palette11.setBrush(QPalette::Active, QPalette::Text, brush);
        palette11.setBrush(QPalette::Active, QPalette::BrightText, brush2);
        palette11.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette11.setBrush(QPalette::Active, QPalette::Base, brush2);
        palette11.setBrush(QPalette::Active, QPalette::Window, brush52);
        palette11.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette11.setBrush(QPalette::Active, QPalette::AlternateBase, brush57);
        palette11.setBrush(QPalette::Active, QPalette::ToolTipBase, brush6);
        palette11.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette11.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette11.setBrush(QPalette::Inactive, QPalette::Button, brush7);
        palette11.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette11.setBrush(QPalette::Inactive, QPalette::Midlight, brush8);
        palette11.setBrush(QPalette::Inactive, QPalette::Dark, brush9);
        palette11.setBrush(QPalette::Inactive, QPalette::Mid, brush10);
        palette11.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette11.setBrush(QPalette::Inactive, QPalette::BrightText, brush2);
        palette11.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette11.setBrush(QPalette::Inactive, QPalette::Base, brush2);
        palette11.setBrush(QPalette::Inactive, QPalette::Window, brush7);
        palette11.setBrush(QPalette::Inactive, QPalette::Shadow, brush11);
        palette11.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush12);
        palette11.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush6);
        palette11.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette11.setBrush(QPalette::Disabled, QPalette::WindowText, brush55);
        palette11.setBrush(QPalette::Disabled, QPalette::Button, brush52);
        palette11.setBrush(QPalette::Disabled, QPalette::Light, brush53);
        palette11.setBrush(QPalette::Disabled, QPalette::Midlight, brush54);
        palette11.setBrush(QPalette::Disabled, QPalette::Dark, brush55);
        palette11.setBrush(QPalette::Disabled, QPalette::Mid, brush56);
        palette11.setBrush(QPalette::Disabled, QPalette::Text, brush55);
        palette11.setBrush(QPalette::Disabled, QPalette::BrightText, brush2);
        palette11.setBrush(QPalette::Disabled, QPalette::ButtonText, brush55);
        palette11.setBrush(QPalette::Disabled, QPalette::Base, brush52);
        palette11.setBrush(QPalette::Disabled, QPalette::Window, brush52);
        palette11.setBrush(QPalette::Disabled, QPalette::Shadow, brush13);
        palette11.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush12);
        palette11.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush6);
        palette11.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        ItemBox->setPalette(palette11);
        inventorycounter = new QLCDNumber(centralwidget);
        inventorycounter->setObjectName(QString::fromUtf8("inventorycounter"));
        inventorycounter->setGeometry(QRect(580, 450, 51, 21));
        QPalette palette12;
        palette12.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette12.setBrush(QPalette::Active, QPalette::Button, brush46);
        palette12.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette12.setBrush(QPalette::Active, QPalette::Midlight, brush47);
        palette12.setBrush(QPalette::Active, QPalette::Dark, brush48);
        palette12.setBrush(QPalette::Active, QPalette::Mid, brush49);
        palette12.setBrush(QPalette::Active, QPalette::Text, brush2);
        palette12.setBrush(QPalette::Active, QPalette::BrightText, brush2);
        palette12.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette12.setBrush(QPalette::Active, QPalette::Base, brush2);
        palette12.setBrush(QPalette::Active, QPalette::Window, brush46);
        palette12.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette12.setBrush(QPalette::Active, QPalette::AlternateBase, brush47);
        palette12.setBrush(QPalette::Active, QPalette::ToolTipBase, brush6);
        palette12.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette12.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette12.setBrush(QPalette::Inactive, QPalette::Button, brush7);
        palette12.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette12.setBrush(QPalette::Inactive, QPalette::Midlight, brush8);
        palette12.setBrush(QPalette::Inactive, QPalette::Dark, brush9);
        palette12.setBrush(QPalette::Inactive, QPalette::Mid, brush10);
        palette12.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette12.setBrush(QPalette::Inactive, QPalette::BrightText, brush2);
        palette12.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette12.setBrush(QPalette::Inactive, QPalette::Base, brush2);
        palette12.setBrush(QPalette::Inactive, QPalette::Window, brush7);
        palette12.setBrush(QPalette::Inactive, QPalette::Shadow, brush11);
        palette12.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush12);
        palette12.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush6);
        palette12.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette12.setBrush(QPalette::Disabled, QPalette::WindowText, brush48);
        palette12.setBrush(QPalette::Disabled, QPalette::Button, brush46);
        palette12.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette12.setBrush(QPalette::Disabled, QPalette::Midlight, brush47);
        palette12.setBrush(QPalette::Disabled, QPalette::Dark, brush48);
        palette12.setBrush(QPalette::Disabled, QPalette::Mid, brush49);
        palette12.setBrush(QPalette::Disabled, QPalette::Text, brush48);
        palette12.setBrush(QPalette::Disabled, QPalette::BrightText, brush2);
        palette12.setBrush(QPalette::Disabled, QPalette::ButtonText, brush48);
        palette12.setBrush(QPalette::Disabled, QPalette::Base, brush46);
        palette12.setBrush(QPalette::Disabled, QPalette::Window, brush46);
        palette12.setBrush(QPalette::Disabled, QPalette::Shadow, brush13);
        palette12.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush12);
        palette12.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush6);
        palette12.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        inventorycounter->setPalette(palette12);
        inventory_label = new QLabel(centralwidget);
        inventory_label->setObjectName(QString::fromUtf8("inventory_label"));
        inventory_label->setGeometry(QRect(430, 410, 121, 41));
        inventory_label->setTextFormat(Qt::AutoText);
        inventory_label->setScaledContents(false);
        InventoryBox = new QComboBox(centralwidget);
        InventoryBox->setObjectName(QString::fromUtf8("InventoryBox"));
        InventoryBox->setGeometry(QRect(360, 450, 211, 25));
        DropButton = new QPushButton(centralwidget);
        DropButton->setObjectName(QString::fromUtf8("DropButton"));
        DropButton->setGeometry(QRect(1040, 400, 131, 61));
        QPalette palette13;
        palette13.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette13.setBrush(QPalette::Active, QPalette::Button, brush46);
        palette13.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette13.setBrush(QPalette::Active, QPalette::Midlight, brush47);
        palette13.setBrush(QPalette::Active, QPalette::Dark, brush48);
        palette13.setBrush(QPalette::Active, QPalette::Mid, brush49);
        palette13.setBrush(QPalette::Active, QPalette::Text, brush);
        palette13.setBrush(QPalette::Active, QPalette::BrightText, brush2);
        palette13.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette13.setBrush(QPalette::Active, QPalette::Base, brush2);
        palette13.setBrush(QPalette::Active, QPalette::Window, brush46);
        palette13.setBrush(QPalette::Active, QPalette::Shadow, brush);
        palette13.setBrush(QPalette::Active, QPalette::AlternateBase, brush47);
        palette13.setBrush(QPalette::Active, QPalette::ToolTipBase, brush6);
        palette13.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        palette13.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette13.setBrush(QPalette::Inactive, QPalette::Button, brush7);
        palette13.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette13.setBrush(QPalette::Inactive, QPalette::Midlight, brush8);
        palette13.setBrush(QPalette::Inactive, QPalette::Dark, brush9);
        palette13.setBrush(QPalette::Inactive, QPalette::Mid, brush10);
        palette13.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette13.setBrush(QPalette::Inactive, QPalette::BrightText, brush2);
        palette13.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette13.setBrush(QPalette::Inactive, QPalette::Base, brush2);
        palette13.setBrush(QPalette::Inactive, QPalette::Window, brush7);
        palette13.setBrush(QPalette::Inactive, QPalette::Shadow, brush11);
        palette13.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush12);
        palette13.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush6);
        palette13.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
        palette13.setBrush(QPalette::Disabled, QPalette::WindowText, brush48);
        palette13.setBrush(QPalette::Disabled, QPalette::Button, brush46);
        palette13.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette13.setBrush(QPalette::Disabled, QPalette::Midlight, brush47);
        palette13.setBrush(QPalette::Disabled, QPalette::Dark, brush48);
        palette13.setBrush(QPalette::Disabled, QPalette::Mid, brush49);
        palette13.setBrush(QPalette::Disabled, QPalette::Text, brush48);
        palette13.setBrush(QPalette::Disabled, QPalette::BrightText, brush2);
        palette13.setBrush(QPalette::Disabled, QPalette::ButtonText, brush48);
        palette13.setBrush(QPalette::Disabled, QPalette::Base, brush46);
        palette13.setBrush(QPalette::Disabled, QPalette::Window, brush46);
        palette13.setBrush(QPalette::Disabled, QPalette::Shadow, brush13);
        palette13.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush12);
        palette13.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush6);
        palette13.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        DropButton->setPalette(palette13);
        DropButton->setFont(font2);
        wordleEdit = new QLineEdit(centralwidget);
        wordleEdit->setObjectName(QString::fromUtf8("wordleEdit"));
        wordleEdit->setGeometry(QRect(370, 550, 201, 25));
        MainWindow->setCentralWidget(centralwidget);
        menubar = new QMenuBar(MainWindow);
        menubar->setObjectName(QString::fromUtf8("menubar"));
        menubar->setGeometry(QRect(0, 0, 1272, 22));
        MainWindow->setMenuBar(menubar);
        statusbar = new QStatusBar(MainWindow);
        statusbar->setObjectName(QString::fromUtf8("statusbar"));
        MainWindow->setStatusBar(statusbar);

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QCoreApplication::translate("MainWindow", "MainWindow", nullptr));
        NorthButton->setText(QCoreApplication::translate("MainWindow", "North", nullptr));
        EastButton->setText(QCoreApplication::translate("MainWindow", "East", nullptr));
        WestButton->setText(QCoreApplication::translate("MainWindow", "West", nullptr));
        SouthButton->setText(QCoreApplication::translate("MainWindow", "South", nullptr));
        dir_label->setText(QCoreApplication::translate("MainWindow", "Location", nullptr));
        MapButton->setText(QCoreApplication::translate("MainWindow", "Map", nullptr));
        imgLabel->setText(QString());
        TeleportButton->setText(QCoreApplication::translate("MainWindow", "Teleport", nullptr));
        TakeButton->setText(QCoreApplication::translate("MainWindow", "Take Item", nullptr));
        inventory_label->setText(QCoreApplication::translate("MainWindow", "Inventory", nullptr));
        DropButton->setText(QCoreApplication::translate("MainWindow", "Drop Current Item", nullptr));
        wordleEdit->setText(QString());
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
