/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 6.0.4
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QLCDNumber>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralwidget;
    QPushButton *NorthButton;
    QPushButton *EastButton;
    QPushButton *WestButton;
    QPushButton *SouthButton;
    QLabel *dir_label;
    QPushButton *MapButton;
    QLabel *imgLabel;
    QComboBox *TeleportBox;
    QPushButton *TeleportButton;
    QPushButton *TakeButton;
    QComboBox *ItemBox;
    QLCDNumber *inventorycounter;
    QLabel *inventory_label;
    QComboBox *InventoryBox;
    QPushButton *DropButton;
    QLineEdit *wordleEdit;
    QLabel *WordleInputLabel;
    QPushButton *AttackButton;
    QMenuBar *menubar;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(1272, 633);
        QPalette palette;
        QBrush brush(QColor(255, 255, 255, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush1(QColor(46, 52, 54, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Button, brush1);
        QBrush brush2(QColor(69, 78, 81, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Light, brush2);
        QBrush brush3(QColor(57, 65, 67, 255));
        brush3.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        QBrush brush4(QColor(23, 26, 27, 255));
        brush4.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Dark, brush4);
        QBrush brush5(QColor(31, 35, 36, 255));
        brush5.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Active, QPalette::Text, brush);
        palette.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        QBrush brush6(QColor(0, 0, 0, 255));
        brush6.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette.setBrush(QPalette::Active, QPalette::Shadow, brush6);
        palette.setBrush(QPalette::Active, QPalette::AlternateBase, brush4);
        QBrush brush7(QColor(255, 255, 220, 255));
        brush7.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::ToolTipBase, brush7);
        palette.setBrush(QPalette::Active, QPalette::ToolTipText, brush6);
        palette.setBrush(QPalette::Inactive, QPalette::WindowText, brush6);
        QBrush brush8(QColor(239, 239, 239, 255));
        brush8.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Inactive, QPalette::Button, brush8);
        palette.setBrush(QPalette::Inactive, QPalette::Light, brush);
        QBrush brush9(QColor(202, 202, 202, 255));
        brush9.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Inactive, QPalette::Midlight, brush9);
        QBrush brush10(QColor(159, 159, 159, 255));
        brush10.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Inactive, QPalette::Dark, brush10);
        QBrush brush11(QColor(184, 184, 184, 255));
        brush11.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Inactive, QPalette::Mid, brush11);
        palette.setBrush(QPalette::Inactive, QPalette::Text, brush6);
        palette.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::ButtonText, brush6);
        palette.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Window, brush8);
        QBrush brush12(QColor(118, 118, 118, 255));
        brush12.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Inactive, QPalette::Shadow, brush12);
        QBrush brush13(QColor(247, 247, 247, 255));
        brush13.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush13);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush7);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush6);
        palette.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        QBrush brush14(QColor(177, 177, 177, 255));
        brush14.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Disabled, QPalette::Shadow, brush14);
        palette.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush13);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush7);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush6);
        MainWindow->setPalette(palette);
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        NorthButton = new QPushButton(centralwidget);
        NorthButton->setObjectName(QString::fromUtf8("NorthButton"));
        NorthButton->setGeometry(QRect(890, 30, 131, 61));
        QPalette palette1;
        palette1.setBrush(QPalette::Active, QPalette::WindowText, brush6);
        QBrush brush15(QColor(237, 212, 0, 255));
        brush15.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Button, brush15);
        QBrush brush16(QColor(255, 239, 100, 255));
        brush16.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Light, brush16);
        QBrush brush17(QColor(246, 225, 50, 255));
        brush17.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Midlight, brush17);
        QBrush brush18(QColor(118, 106, 0, 255));
        brush18.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Dark, brush18);
        QBrush brush19(QColor(158, 141, 0, 255));
        brush19.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Mid, brush19);
        palette1.setBrush(QPalette::Active, QPalette::Text, brush6);
        palette1.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette1.setBrush(QPalette::Active, QPalette::ButtonText, brush6);
        palette1.setBrush(QPalette::Active, QPalette::Base, brush);
        palette1.setBrush(QPalette::Active, QPalette::Window, brush15);
        palette1.setBrush(QPalette::Active, QPalette::Shadow, brush6);
        QBrush brush20(QColor(246, 233, 127, 255));
        brush20.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::AlternateBase, brush20);
        palette1.setBrush(QPalette::Active, QPalette::ToolTipBase, brush7);
        palette1.setBrush(QPalette::Active, QPalette::ToolTipText, brush6);
        palette1.setBrush(QPalette::Inactive, QPalette::WindowText, brush6);
        palette1.setBrush(QPalette::Inactive, QPalette::Button, brush8);
        palette1.setBrush(QPalette::Inactive, QPalette::Light, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Midlight, brush9);
        palette1.setBrush(QPalette::Inactive, QPalette::Dark, brush10);
        palette1.setBrush(QPalette::Inactive, QPalette::Mid, brush11);
        palette1.setBrush(QPalette::Inactive, QPalette::Text, brush6);
        palette1.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::ButtonText, brush6);
        palette1.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Window, brush8);
        palette1.setBrush(QPalette::Inactive, QPalette::Shadow, brush12);
        palette1.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush13);
        palette1.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush7);
        palette1.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush6);
        palette1.setBrush(QPalette::Disabled, QPalette::WindowText, brush18);
        palette1.setBrush(QPalette::Disabled, QPalette::Button, brush15);
        palette1.setBrush(QPalette::Disabled, QPalette::Light, brush16);
        palette1.setBrush(QPalette::Disabled, QPalette::Midlight, brush17);
        palette1.setBrush(QPalette::Disabled, QPalette::Dark, brush18);
        palette1.setBrush(QPalette::Disabled, QPalette::Mid, brush19);
        palette1.setBrush(QPalette::Disabled, QPalette::Text, brush18);
        palette1.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::ButtonText, brush18);
        palette1.setBrush(QPalette::Disabled, QPalette::Base, brush15);
        palette1.setBrush(QPalette::Disabled, QPalette::Window, brush15);
        palette1.setBrush(QPalette::Disabled, QPalette::Shadow, brush14);
        palette1.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush13);
        palette1.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush7);
        palette1.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush6);
        NorthButton->setPalette(palette1);
        QFont font;
        font.setPointSize(15);
        font.setBold(true);
        font.setItalic(false);
        font.setKerning(true);
        NorthButton->setFont(font);
        EastButton = new QPushButton(centralwidget);
        EastButton->setObjectName(QString::fromUtf8("EastButton"));
        EastButton->setGeometry(QRect(1030, 140, 131, 61));
        QPalette palette2;
        palette2.setBrush(QPalette::Active, QPalette::WindowText, brush6);
        QBrush brush21(QColor(204, 0, 0, 255));
        brush21.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::Button, brush21);
        QBrush brush22(QColor(255, 51, 51, 255));
        brush22.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::Light, brush22);
        QBrush brush23(QColor(229, 25, 25, 255));
        brush23.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::Midlight, brush23);
        QBrush brush24(QColor(102, 0, 0, 255));
        brush24.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::Dark, brush24);
        QBrush brush25(QColor(136, 0, 0, 255));
        brush25.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::Mid, brush25);
        palette2.setBrush(QPalette::Active, QPalette::Text, brush6);
        palette2.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette2.setBrush(QPalette::Active, QPalette::ButtonText, brush6);
        palette2.setBrush(QPalette::Active, QPalette::Base, brush);
        palette2.setBrush(QPalette::Active, QPalette::Window, brush21);
        palette2.setBrush(QPalette::Active, QPalette::Shadow, brush6);
        QBrush brush26(QColor(229, 127, 127, 255));
        brush26.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::AlternateBase, brush26);
        palette2.setBrush(QPalette::Active, QPalette::ToolTipBase, brush7);
        palette2.setBrush(QPalette::Active, QPalette::ToolTipText, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::WindowText, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::Button, brush8);
        palette2.setBrush(QPalette::Inactive, QPalette::Light, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Midlight, brush9);
        palette2.setBrush(QPalette::Inactive, QPalette::Dark, brush10);
        palette2.setBrush(QPalette::Inactive, QPalette::Mid, brush11);
        palette2.setBrush(QPalette::Inactive, QPalette::Text, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::ButtonText, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Window, brush8);
        palette2.setBrush(QPalette::Inactive, QPalette::Shadow, brush12);
        palette2.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush13);
        palette2.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush7);
        palette2.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush6);
        palette2.setBrush(QPalette::Disabled, QPalette::WindowText, brush24);
        palette2.setBrush(QPalette::Disabled, QPalette::Button, brush21);
        palette2.setBrush(QPalette::Disabled, QPalette::Light, brush22);
        palette2.setBrush(QPalette::Disabled, QPalette::Midlight, brush23);
        palette2.setBrush(QPalette::Disabled, QPalette::Dark, brush24);
        palette2.setBrush(QPalette::Disabled, QPalette::Mid, brush25);
        palette2.setBrush(QPalette::Disabled, QPalette::Text, brush24);
        palette2.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::ButtonText, brush24);
        palette2.setBrush(QPalette::Disabled, QPalette::Base, brush21);
        palette2.setBrush(QPalette::Disabled, QPalette::Window, brush21);
        palette2.setBrush(QPalette::Disabled, QPalette::Shadow, brush14);
        palette2.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush13);
        palette2.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush7);
        palette2.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush6);
        EastButton->setPalette(palette2);
        QFont font1;
        font1.setPointSize(15);
        font1.setBold(true);
        EastButton->setFont(font1);
        WestButton = new QPushButton(centralwidget);
        WestButton->setObjectName(QString::fromUtf8("WestButton"));
        WestButton->setGeometry(QRect(750, 140, 131, 61));
        QPalette palette3;
        palette3.setBrush(QPalette::Active, QPalette::WindowText, brush6);
        QBrush brush27(QColor(52, 101, 164, 255));
        brush27.setStyle(Qt::SolidPattern);
        palette3.setBrush(QPalette::Active, QPalette::Button, brush27);
        QBrush brush28(QColor(78, 151, 246, 255));
        brush28.setStyle(Qt::SolidPattern);
        palette3.setBrush(QPalette::Active, QPalette::Light, brush28);
        QBrush brush29(QColor(65, 126, 205, 255));
        brush29.setStyle(Qt::SolidPattern);
        palette3.setBrush(QPalette::Active, QPalette::Midlight, brush29);
        QBrush brush30(QColor(26, 50, 82, 255));
        brush30.setStyle(Qt::SolidPattern);
        palette3.setBrush(QPalette::Active, QPalette::Dark, brush30);
        QBrush brush31(QColor(35, 67, 109, 255));
        brush31.setStyle(Qt::SolidPattern);
        palette3.setBrush(QPalette::Active, QPalette::Mid, brush31);
        palette3.setBrush(QPalette::Active, QPalette::Text, brush6);
        palette3.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette3.setBrush(QPalette::Active, QPalette::ButtonText, brush6);
        palette3.setBrush(QPalette::Active, QPalette::Base, brush);
        palette3.setBrush(QPalette::Active, QPalette::Window, brush27);
        palette3.setBrush(QPalette::Active, QPalette::Shadow, brush6);
        QBrush brush32(QColor(153, 178, 209, 255));
        brush32.setStyle(Qt::SolidPattern);
        palette3.setBrush(QPalette::Active, QPalette::AlternateBase, brush32);
        palette3.setBrush(QPalette::Active, QPalette::ToolTipBase, brush7);
        palette3.setBrush(QPalette::Active, QPalette::ToolTipText, brush6);
        palette3.setBrush(QPalette::Inactive, QPalette::WindowText, brush6);
        palette3.setBrush(QPalette::Inactive, QPalette::Button, brush8);
        palette3.setBrush(QPalette::Inactive, QPalette::Light, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Midlight, brush9);
        palette3.setBrush(QPalette::Inactive, QPalette::Dark, brush10);
        palette3.setBrush(QPalette::Inactive, QPalette::Mid, brush11);
        palette3.setBrush(QPalette::Inactive, QPalette::Text, brush6);
        palette3.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::ButtonText, brush6);
        palette3.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Window, brush8);
        palette3.setBrush(QPalette::Inactive, QPalette::Shadow, brush12);
        palette3.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush13);
        palette3.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush7);
        palette3.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush6);
        palette3.setBrush(QPalette::Disabled, QPalette::WindowText, brush30);
        palette3.setBrush(QPalette::Disabled, QPalette::Button, brush27);
        palette3.setBrush(QPalette::Disabled, QPalette::Light, brush28);
        palette3.setBrush(QPalette::Disabled, QPalette::Midlight, brush29);
        palette3.setBrush(QPalette::Disabled, QPalette::Dark, brush30);
        palette3.setBrush(QPalette::Disabled, QPalette::Mid, brush31);
        palette3.setBrush(QPalette::Disabled, QPalette::Text, brush30);
        palette3.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::ButtonText, brush30);
        palette3.setBrush(QPalette::Disabled, QPalette::Base, brush27);
        palette3.setBrush(QPalette::Disabled, QPalette::Window, brush27);
        palette3.setBrush(QPalette::Disabled, QPalette::Shadow, brush14);
        palette3.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush13);
        palette3.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush7);
        palette3.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush6);
        WestButton->setPalette(palette3);
        WestButton->setFont(font1);
        WestButton->setFlat(false);
        SouthButton = new QPushButton(centralwidget);
        SouthButton->setObjectName(QString::fromUtf8("SouthButton"));
        SouthButton->setGeometry(QRect(890, 250, 131, 61));
        QPalette palette4;
        palette4.setBrush(QPalette::Active, QPalette::WindowText, brush6);
        QBrush brush33(QColor(78, 154, 6, 255));
        brush33.setStyle(Qt::SolidPattern);
        palette4.setBrush(QPalette::Active, QPalette::Button, brush33);
        QBrush brush34(QColor(117, 231, 9, 255));
        brush34.setStyle(Qt::SolidPattern);
        palette4.setBrush(QPalette::Active, QPalette::Light, brush34);
        QBrush brush35(QColor(97, 192, 7, 255));
        brush35.setStyle(Qt::SolidPattern);
        palette4.setBrush(QPalette::Active, QPalette::Midlight, brush35);
        QBrush brush36(QColor(39, 77, 3, 255));
        brush36.setStyle(Qt::SolidPattern);
        palette4.setBrush(QPalette::Active, QPalette::Dark, brush36);
        QBrush brush37(QColor(52, 103, 4, 255));
        brush37.setStyle(Qt::SolidPattern);
        palette4.setBrush(QPalette::Active, QPalette::Mid, brush37);
        palette4.setBrush(QPalette::Active, QPalette::Text, brush6);
        palette4.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette4.setBrush(QPalette::Active, QPalette::ButtonText, brush6);
        palette4.setBrush(QPalette::Active, QPalette::Base, brush);
        palette4.setBrush(QPalette::Active, QPalette::Window, brush33);
        palette4.setBrush(QPalette::Active, QPalette::Shadow, brush6);
        QBrush brush38(QColor(166, 204, 130, 255));
        brush38.setStyle(Qt::SolidPattern);
        palette4.setBrush(QPalette::Active, QPalette::AlternateBase, brush38);
        palette4.setBrush(QPalette::Active, QPalette::ToolTipBase, brush7);
        palette4.setBrush(QPalette::Active, QPalette::ToolTipText, brush6);
        palette4.setBrush(QPalette::Inactive, QPalette::WindowText, brush6);
        palette4.setBrush(QPalette::Inactive, QPalette::Button, brush8);
        palette4.setBrush(QPalette::Inactive, QPalette::Light, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Midlight, brush9);
        palette4.setBrush(QPalette::Inactive, QPalette::Dark, brush10);
        palette4.setBrush(QPalette::Inactive, QPalette::Mid, brush11);
        palette4.setBrush(QPalette::Inactive, QPalette::Text, brush6);
        palette4.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::ButtonText, brush6);
        palette4.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Window, brush8);
        palette4.setBrush(QPalette::Inactive, QPalette::Shadow, brush12);
        palette4.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush13);
        palette4.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush7);
        palette4.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush6);
        palette4.setBrush(QPalette::Disabled, QPalette::WindowText, brush36);
        palette4.setBrush(QPalette::Disabled, QPalette::Button, brush33);
        palette4.setBrush(QPalette::Disabled, QPalette::Light, brush34);
        palette4.setBrush(QPalette::Disabled, QPalette::Midlight, brush35);
        palette4.setBrush(QPalette::Disabled, QPalette::Dark, brush36);
        palette4.setBrush(QPalette::Disabled, QPalette::Mid, brush37);
        palette4.setBrush(QPalette::Disabled, QPalette::Text, brush36);
        palette4.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::ButtonText, brush36);
        palette4.setBrush(QPalette::Disabled, QPalette::Base, brush33);
        palette4.setBrush(QPalette::Disabled, QPalette::Window, brush33);
        palette4.setBrush(QPalette::Disabled, QPalette::Shadow, brush14);
        palette4.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush13);
        palette4.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush7);
        palette4.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush6);
        SouthButton->setPalette(palette4);
        SouthButton->setFont(font1);
        dir_label = new QLabel(centralwidget);
        dir_label->setObjectName(QString::fromUtf8("dir_label"));
        dir_label->setGeometry(QRect(50, 330, 541, 161));
        QPalette palette5;
        palette5.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette5.setBrush(QPalette::Active, QPalette::Button, brush8);
        palette5.setBrush(QPalette::Active, QPalette::Light, brush);
        palette5.setBrush(QPalette::Active, QPalette::Midlight, brush9);
        palette5.setBrush(QPalette::Active, QPalette::Dark, brush10);
        palette5.setBrush(QPalette::Active, QPalette::Mid, brush11);
        palette5.setBrush(QPalette::Active, QPalette::Text, brush6);
        palette5.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette5.setBrush(QPalette::Active, QPalette::ButtonText, brush6);
        palette5.setBrush(QPalette::Active, QPalette::Base, brush);
        palette5.setBrush(QPalette::Active, QPalette::Window, brush8);
        palette5.setBrush(QPalette::Active, QPalette::Shadow, brush12);
        QBrush brush39(QColor(48, 140, 198, 255));
        brush39.setStyle(Qt::SolidPattern);
        palette5.setBrush(QPalette::Active, QPalette::Highlight, brush39);
        palette5.setBrush(QPalette::Active, QPalette::HighlightedText, brush);
        QBrush brush40(QColor(0, 0, 255, 255));
        brush40.setStyle(Qt::SolidPattern);
        palette5.setBrush(QPalette::Active, QPalette::Link, brush40);
        QBrush brush41(QColor(255, 0, 255, 255));
        brush41.setStyle(Qt::SolidPattern);
        palette5.setBrush(QPalette::Active, QPalette::LinkVisited, brush41);
        palette5.setBrush(QPalette::Active, QPalette::AlternateBase, brush13);
        palette5.setBrush(QPalette::Active, QPalette::NoRole, brush6);
        palette5.setBrush(QPalette::Active, QPalette::ToolTipBase, brush7);
        palette5.setBrush(QPalette::Active, QPalette::ToolTipText, brush6);
        QBrush brush42(QColor(0, 0, 0, 128));
        brush42.setStyle(Qt::SolidPattern);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette5.setBrush(QPalette::Active, QPalette::PlaceholderText, brush42);
#endif
        palette5.setBrush(QPalette::Inactive, QPalette::WindowText, brush6);
        palette5.setBrush(QPalette::Inactive, QPalette::Button, brush8);
        palette5.setBrush(QPalette::Inactive, QPalette::Light, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::Midlight, brush9);
        palette5.setBrush(QPalette::Inactive, QPalette::Dark, brush10);
        palette5.setBrush(QPalette::Inactive, QPalette::Mid, brush11);
        palette5.setBrush(QPalette::Inactive, QPalette::Text, brush6);
        palette5.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::ButtonText, brush6);
        palette5.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::Window, brush8);
        palette5.setBrush(QPalette::Inactive, QPalette::Shadow, brush12);
        palette5.setBrush(QPalette::Inactive, QPalette::Highlight, brush39);
        palette5.setBrush(QPalette::Inactive, QPalette::HighlightedText, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::Link, brush40);
        palette5.setBrush(QPalette::Inactive, QPalette::LinkVisited, brush41);
        palette5.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush13);
        QBrush brush43(QColor(0, 0, 0, 255));
        brush43.setStyle(Qt::NoBrush);
        palette5.setBrush(QPalette::Inactive, QPalette::NoRole, brush43);
        palette5.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush7);
        palette5.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush6);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette5.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush42);
#endif
        QBrush brush44(QColor(190, 190, 190, 255));
        brush44.setStyle(Qt::SolidPattern);
        palette5.setBrush(QPalette::Disabled, QPalette::WindowText, brush44);
        palette5.setBrush(QPalette::Disabled, QPalette::Button, brush8);
        palette5.setBrush(QPalette::Disabled, QPalette::Light, brush);
        palette5.setBrush(QPalette::Disabled, QPalette::Midlight, brush9);
        palette5.setBrush(QPalette::Disabled, QPalette::Dark, brush44);
        palette5.setBrush(QPalette::Disabled, QPalette::Mid, brush11);
        palette5.setBrush(QPalette::Disabled, QPalette::Text, brush44);
        palette5.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette5.setBrush(QPalette::Disabled, QPalette::ButtonText, brush44);
        palette5.setBrush(QPalette::Disabled, QPalette::Base, brush8);
        palette5.setBrush(QPalette::Disabled, QPalette::Window, brush8);
        palette5.setBrush(QPalette::Disabled, QPalette::Shadow, brush14);
        QBrush brush45(QColor(145, 145, 145, 255));
        brush45.setStyle(Qt::SolidPattern);
        palette5.setBrush(QPalette::Disabled, QPalette::Highlight, brush45);
        palette5.setBrush(QPalette::Disabled, QPalette::HighlightedText, brush);
        palette5.setBrush(QPalette::Disabled, QPalette::Link, brush40);
        palette5.setBrush(QPalette::Disabled, QPalette::LinkVisited, brush41);
        palette5.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush13);
        QBrush brush46(QColor(0, 0, 0, 255));
        brush46.setStyle(Qt::NoBrush);
        palette5.setBrush(QPalette::Disabled, QPalette::NoRole, brush46);
        palette5.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush7);
        palette5.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush6);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette5.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush42);
#endif
        dir_label->setPalette(palette5);
        dir_label->setFrameShape(QFrame::Box);
        dir_label->setLineWidth(2);
        dir_label->setAlignment(Qt::AlignCenter);
        MapButton = new QPushButton(centralwidget);
        MapButton->setObjectName(QString::fromUtf8("MapButton"));
        MapButton->setGeometry(QRect(890, 140, 131, 61));
        QPalette palette6;
        palette6.setBrush(QPalette::Active, QPalette::WindowText, brush6);
        QBrush brush47(QColor(144, 214, 242, 255));
        brush47.setStyle(Qt::SolidPattern);
        palette6.setBrush(QPalette::Active, QPalette::Button, brush47);
        palette6.setBrush(QPalette::Active, QPalette::Light, brush);
        QBrush brush48(QColor(199, 234, 248, 255));
        brush48.setStyle(Qt::SolidPattern);
        palette6.setBrush(QPalette::Active, QPalette::Midlight, brush48);
        QBrush brush49(QColor(72, 107, 121, 255));
        brush49.setStyle(Qt::SolidPattern);
        palette6.setBrush(QPalette::Active, QPalette::Dark, brush49);
        QBrush brush50(QColor(96, 143, 161, 255));
        brush50.setStyle(Qt::SolidPattern);
        palette6.setBrush(QPalette::Active, QPalette::Mid, brush50);
        palette6.setBrush(QPalette::Active, QPalette::Text, brush6);
        palette6.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette6.setBrush(QPalette::Active, QPalette::ButtonText, brush6);
        palette6.setBrush(QPalette::Active, QPalette::Base, brush);
        palette6.setBrush(QPalette::Active, QPalette::Window, brush47);
        palette6.setBrush(QPalette::Active, QPalette::Shadow, brush6);
        palette6.setBrush(QPalette::Active, QPalette::AlternateBase, brush48);
        palette6.setBrush(QPalette::Active, QPalette::ToolTipBase, brush7);
        palette6.setBrush(QPalette::Active, QPalette::ToolTipText, brush6);
        palette6.setBrush(QPalette::Inactive, QPalette::WindowText, brush6);
        palette6.setBrush(QPalette::Inactive, QPalette::Button, brush8);
        palette6.setBrush(QPalette::Inactive, QPalette::Light, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::Midlight, brush9);
        palette6.setBrush(QPalette::Inactive, QPalette::Dark, brush10);
        palette6.setBrush(QPalette::Inactive, QPalette::Mid, brush11);
        palette6.setBrush(QPalette::Inactive, QPalette::Text, brush6);
        palette6.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::ButtonText, brush6);
        palette6.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::Window, brush8);
        palette6.setBrush(QPalette::Inactive, QPalette::Shadow, brush12);
        palette6.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush13);
        palette6.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush7);
        palette6.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush6);
        palette6.setBrush(QPalette::Disabled, QPalette::WindowText, brush49);
        palette6.setBrush(QPalette::Disabled, QPalette::Button, brush47);
        palette6.setBrush(QPalette::Disabled, QPalette::Light, brush);
        palette6.setBrush(QPalette::Disabled, QPalette::Midlight, brush48);
        palette6.setBrush(QPalette::Disabled, QPalette::Dark, brush49);
        palette6.setBrush(QPalette::Disabled, QPalette::Mid, brush50);
        palette6.setBrush(QPalette::Disabled, QPalette::Text, brush49);
        palette6.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette6.setBrush(QPalette::Disabled, QPalette::ButtonText, brush49);
        palette6.setBrush(QPalette::Disabled, QPalette::Base, brush47);
        palette6.setBrush(QPalette::Disabled, QPalette::Window, brush47);
        palette6.setBrush(QPalette::Disabled, QPalette::Shadow, brush14);
        palette6.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush13);
        palette6.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush7);
        palette6.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush6);
        MapButton->setPalette(palette6);
        QFont font2;
        MapButton->setFont(font2);
        imgLabel = new QLabel(centralwidget);
        imgLabel->setObjectName(QString::fromUtf8("imgLabel"));
        imgLabel->setGeometry(QRect(40, 10, 561, 311));
        QPalette palette7;
        palette7.setBrush(QPalette::Active, QPalette::WindowText, brush6);
        palette7.setBrush(QPalette::Active, QPalette::Button, brush8);
        palette7.setBrush(QPalette::Active, QPalette::Light, brush);
        palette7.setBrush(QPalette::Active, QPalette::Midlight, brush9);
        palette7.setBrush(QPalette::Active, QPalette::Dark, brush10);
        palette7.setBrush(QPalette::Active, QPalette::Mid, brush11);
        palette7.setBrush(QPalette::Active, QPalette::Text, brush6);
        palette7.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette7.setBrush(QPalette::Active, QPalette::ButtonText, brush6);
        palette7.setBrush(QPalette::Active, QPalette::Base, brush);
        palette7.setBrush(QPalette::Active, QPalette::Window, brush8);
        palette7.setBrush(QPalette::Active, QPalette::Shadow, brush12);
        palette7.setBrush(QPalette::Active, QPalette::Highlight, brush39);
        palette7.setBrush(QPalette::Active, QPalette::HighlightedText, brush);
        palette7.setBrush(QPalette::Active, QPalette::Link, brush40);
        palette7.setBrush(QPalette::Active, QPalette::LinkVisited, brush41);
        palette7.setBrush(QPalette::Active, QPalette::AlternateBase, brush13);
        palette7.setBrush(QPalette::Active, QPalette::NoRole, brush6);
        palette7.setBrush(QPalette::Active, QPalette::ToolTipBase, brush7);
        palette7.setBrush(QPalette::Active, QPalette::ToolTipText, brush6);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette7.setBrush(QPalette::Active, QPalette::PlaceholderText, brush42);
#endif
        palette7.setBrush(QPalette::Inactive, QPalette::WindowText, brush6);
        palette7.setBrush(QPalette::Inactive, QPalette::Button, brush8);
        palette7.setBrush(QPalette::Inactive, QPalette::Light, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::Midlight, brush9);
        palette7.setBrush(QPalette::Inactive, QPalette::Dark, brush10);
        palette7.setBrush(QPalette::Inactive, QPalette::Mid, brush11);
        palette7.setBrush(QPalette::Inactive, QPalette::Text, brush6);
        palette7.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::ButtonText, brush6);
        palette7.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::Window, brush8);
        palette7.setBrush(QPalette::Inactive, QPalette::Shadow, brush12);
        palette7.setBrush(QPalette::Inactive, QPalette::Highlight, brush39);
        palette7.setBrush(QPalette::Inactive, QPalette::HighlightedText, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::Link, brush40);
        palette7.setBrush(QPalette::Inactive, QPalette::LinkVisited, brush41);
        palette7.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush13);
        QBrush brush51(QColor(0, 0, 0, 255));
        brush51.setStyle(Qt::NoBrush);
        palette7.setBrush(QPalette::Inactive, QPalette::NoRole, brush51);
        palette7.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush7);
        palette7.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush6);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette7.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush42);
#endif
        palette7.setBrush(QPalette::Disabled, QPalette::WindowText, brush44);
        palette7.setBrush(QPalette::Disabled, QPalette::Button, brush8);
        palette7.setBrush(QPalette::Disabled, QPalette::Light, brush);
        palette7.setBrush(QPalette::Disabled, QPalette::Midlight, brush9);
        palette7.setBrush(QPalette::Disabled, QPalette::Dark, brush44);
        palette7.setBrush(QPalette::Disabled, QPalette::Mid, brush11);
        palette7.setBrush(QPalette::Disabled, QPalette::Text, brush44);
        palette7.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette7.setBrush(QPalette::Disabled, QPalette::ButtonText, brush44);
        palette7.setBrush(QPalette::Disabled, QPalette::Base, brush8);
        palette7.setBrush(QPalette::Disabled, QPalette::Window, brush8);
        palette7.setBrush(QPalette::Disabled, QPalette::Shadow, brush14);
        palette7.setBrush(QPalette::Disabled, QPalette::Highlight, brush45);
        palette7.setBrush(QPalette::Disabled, QPalette::HighlightedText, brush);
        palette7.setBrush(QPalette::Disabled, QPalette::Link, brush40);
        palette7.setBrush(QPalette::Disabled, QPalette::LinkVisited, brush41);
        palette7.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush13);
        QBrush brush52(QColor(0, 0, 0, 255));
        brush52.setStyle(Qt::NoBrush);
        palette7.setBrush(QPalette::Disabled, QPalette::NoRole, brush52);
        palette7.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush7);
        palette7.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush6);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette7.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush42);
#endif
        imgLabel->setPalette(palette7);
        imgLabel->setFrameShape(QFrame::Panel);
        imgLabel->setFrameShadow(QFrame::Raised);
        imgLabel->setLineWidth(6);
        TeleportBox = new QComboBox(centralwidget);
        TeleportBox->setObjectName(QString::fromUtf8("TeleportBox"));
        TeleportBox->setGeometry(QRect(750, 90, 131, 25));
        QPalette palette8;
        palette8.setBrush(QPalette::Active, QPalette::WindowText, brush6);
        QBrush brush53(QColor(114, 159, 207, 255));
        brush53.setStyle(Qt::SolidPattern);
        palette8.setBrush(QPalette::Active, QPalette::Button, brush53);
        QBrush brush54(QColor(196, 225, 255, 255));
        brush54.setStyle(Qt::SolidPattern);
        palette8.setBrush(QPalette::Active, QPalette::Light, brush54);
        QBrush brush55(QColor(155, 192, 231, 255));
        brush55.setStyle(Qt::SolidPattern);
        palette8.setBrush(QPalette::Active, QPalette::Midlight, brush55);
        QBrush brush56(QColor(57, 79, 103, 255));
        brush56.setStyle(Qt::SolidPattern);
        palette8.setBrush(QPalette::Active, QPalette::Dark, brush56);
        QBrush brush57(QColor(76, 106, 138, 255));
        brush57.setStyle(Qt::SolidPattern);
        palette8.setBrush(QPalette::Active, QPalette::Mid, brush57);
        palette8.setBrush(QPalette::Active, QPalette::Text, brush6);
        palette8.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette8.setBrush(QPalette::Active, QPalette::ButtonText, brush6);
        palette8.setBrush(QPalette::Active, QPalette::Base, brush);
        palette8.setBrush(QPalette::Active, QPalette::Window, brush53);
        palette8.setBrush(QPalette::Active, QPalette::Shadow, brush6);
        QBrush brush58(QColor(184, 207, 231, 255));
        brush58.setStyle(Qt::SolidPattern);
        palette8.setBrush(QPalette::Active, QPalette::AlternateBase, brush58);
        palette8.setBrush(QPalette::Active, QPalette::ToolTipBase, brush7);
        palette8.setBrush(QPalette::Active, QPalette::ToolTipText, brush6);
        palette8.setBrush(QPalette::Inactive, QPalette::WindowText, brush6);
        palette8.setBrush(QPalette::Inactive, QPalette::Button, brush8);
        palette8.setBrush(QPalette::Inactive, QPalette::Light, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::Midlight, brush9);
        palette8.setBrush(QPalette::Inactive, QPalette::Dark, brush10);
        palette8.setBrush(QPalette::Inactive, QPalette::Mid, brush11);
        palette8.setBrush(QPalette::Inactive, QPalette::Text, brush6);
        palette8.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::ButtonText, brush6);
        palette8.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::Window, brush8);
        palette8.setBrush(QPalette::Inactive, QPalette::Shadow, brush12);
        palette8.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush13);
        palette8.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush7);
        palette8.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush6);
        palette8.setBrush(QPalette::Disabled, QPalette::WindowText, brush56);
        palette8.setBrush(QPalette::Disabled, QPalette::Button, brush53);
        palette8.setBrush(QPalette::Disabled, QPalette::Light, brush54);
        palette8.setBrush(QPalette::Disabled, QPalette::Midlight, brush55);
        palette8.setBrush(QPalette::Disabled, QPalette::Dark, brush56);
        palette8.setBrush(QPalette::Disabled, QPalette::Mid, brush57);
        palette8.setBrush(QPalette::Disabled, QPalette::Text, brush56);
        palette8.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette8.setBrush(QPalette::Disabled, QPalette::ButtonText, brush56);
        palette8.setBrush(QPalette::Disabled, QPalette::Base, brush53);
        palette8.setBrush(QPalette::Disabled, QPalette::Window, brush53);
        palette8.setBrush(QPalette::Disabled, QPalette::Shadow, brush14);
        palette8.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush13);
        palette8.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush7);
        palette8.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush6);
        TeleportBox->setPalette(palette8);
        TeleportButton = new QPushButton(centralwidget);
        TeleportButton->setObjectName(QString::fromUtf8("TeleportButton"));
        TeleportButton->setGeometry(QRect(750, 30, 131, 61));
        QPalette palette9;
        palette9.setBrush(QPalette::Active, QPalette::WindowText, brush6);
        palette9.setBrush(QPalette::Active, QPalette::Button, brush47);
        palette9.setBrush(QPalette::Active, QPalette::Light, brush);
        palette9.setBrush(QPalette::Active, QPalette::Midlight, brush48);
        palette9.setBrush(QPalette::Active, QPalette::Dark, brush49);
        palette9.setBrush(QPalette::Active, QPalette::Mid, brush50);
        palette9.setBrush(QPalette::Active, QPalette::Text, brush6);
        palette9.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette9.setBrush(QPalette::Active, QPalette::ButtonText, brush6);
        palette9.setBrush(QPalette::Active, QPalette::Base, brush);
        palette9.setBrush(QPalette::Active, QPalette::Window, brush47);
        palette9.setBrush(QPalette::Active, QPalette::Shadow, brush6);
        palette9.setBrush(QPalette::Active, QPalette::AlternateBase, brush48);
        palette9.setBrush(QPalette::Active, QPalette::ToolTipBase, brush7);
        palette9.setBrush(QPalette::Active, QPalette::ToolTipText, brush6);
        palette9.setBrush(QPalette::Inactive, QPalette::WindowText, brush6);
        palette9.setBrush(QPalette::Inactive, QPalette::Button, brush8);
        palette9.setBrush(QPalette::Inactive, QPalette::Light, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::Midlight, brush9);
        palette9.setBrush(QPalette::Inactive, QPalette::Dark, brush10);
        palette9.setBrush(QPalette::Inactive, QPalette::Mid, brush11);
        palette9.setBrush(QPalette::Inactive, QPalette::Text, brush6);
        palette9.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::ButtonText, brush6);
        palette9.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::Window, brush8);
        palette9.setBrush(QPalette::Inactive, QPalette::Shadow, brush12);
        palette9.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush13);
        palette9.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush7);
        palette9.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush6);
        palette9.setBrush(QPalette::Disabled, QPalette::WindowText, brush49);
        palette9.setBrush(QPalette::Disabled, QPalette::Button, brush47);
        palette9.setBrush(QPalette::Disabled, QPalette::Light, brush);
        palette9.setBrush(QPalette::Disabled, QPalette::Midlight, brush48);
        palette9.setBrush(QPalette::Disabled, QPalette::Dark, brush49);
        palette9.setBrush(QPalette::Disabled, QPalette::Mid, brush50);
        palette9.setBrush(QPalette::Disabled, QPalette::Text, brush49);
        palette9.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette9.setBrush(QPalette::Disabled, QPalette::ButtonText, brush49);
        palette9.setBrush(QPalette::Disabled, QPalette::Base, brush47);
        palette9.setBrush(QPalette::Disabled, QPalette::Window, brush47);
        palette9.setBrush(QPalette::Disabled, QPalette::Shadow, brush14);
        palette9.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush13);
        palette9.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush7);
        palette9.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush6);
        TeleportButton->setPalette(palette9);
        TeleportButton->setFont(font2);
        TakeButton = new QPushButton(centralwidget);
        TakeButton->setObjectName(QString::fromUtf8("TakeButton"));
        TakeButton->setGeometry(QRect(750, 250, 131, 61));
        QPalette palette10;
        palette10.setBrush(QPalette::Active, QPalette::WindowText, brush6);
        palette10.setBrush(QPalette::Active, QPalette::Button, brush47);
        palette10.setBrush(QPalette::Active, QPalette::Light, brush);
        palette10.setBrush(QPalette::Active, QPalette::Midlight, brush48);
        palette10.setBrush(QPalette::Active, QPalette::Dark, brush49);
        palette10.setBrush(QPalette::Active, QPalette::Mid, brush50);
        palette10.setBrush(QPalette::Active, QPalette::Text, brush6);
        palette10.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette10.setBrush(QPalette::Active, QPalette::ButtonText, brush6);
        palette10.setBrush(QPalette::Active, QPalette::Base, brush);
        palette10.setBrush(QPalette::Active, QPalette::Window, brush47);
        palette10.setBrush(QPalette::Active, QPalette::Shadow, brush6);
        palette10.setBrush(QPalette::Active, QPalette::AlternateBase, brush48);
        palette10.setBrush(QPalette::Active, QPalette::ToolTipBase, brush7);
        palette10.setBrush(QPalette::Active, QPalette::ToolTipText, brush6);
        palette10.setBrush(QPalette::Inactive, QPalette::WindowText, brush6);
        palette10.setBrush(QPalette::Inactive, QPalette::Button, brush8);
        palette10.setBrush(QPalette::Inactive, QPalette::Light, brush);
        palette10.setBrush(QPalette::Inactive, QPalette::Midlight, brush9);
        palette10.setBrush(QPalette::Inactive, QPalette::Dark, brush10);
        palette10.setBrush(QPalette::Inactive, QPalette::Mid, brush11);
        palette10.setBrush(QPalette::Inactive, QPalette::Text, brush6);
        palette10.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette10.setBrush(QPalette::Inactive, QPalette::ButtonText, brush6);
        palette10.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette10.setBrush(QPalette::Inactive, QPalette::Window, brush8);
        palette10.setBrush(QPalette::Inactive, QPalette::Shadow, brush12);
        palette10.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush13);
        palette10.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush7);
        palette10.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush6);
        palette10.setBrush(QPalette::Disabled, QPalette::WindowText, brush49);
        palette10.setBrush(QPalette::Disabled, QPalette::Button, brush47);
        palette10.setBrush(QPalette::Disabled, QPalette::Light, brush);
        palette10.setBrush(QPalette::Disabled, QPalette::Midlight, brush48);
        palette10.setBrush(QPalette::Disabled, QPalette::Dark, brush49);
        palette10.setBrush(QPalette::Disabled, QPalette::Mid, brush50);
        palette10.setBrush(QPalette::Disabled, QPalette::Text, brush49);
        palette10.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette10.setBrush(QPalette::Disabled, QPalette::ButtonText, brush49);
        palette10.setBrush(QPalette::Disabled, QPalette::Base, brush47);
        palette10.setBrush(QPalette::Disabled, QPalette::Window, brush47);
        palette10.setBrush(QPalette::Disabled, QPalette::Shadow, brush14);
        palette10.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush13);
        palette10.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush7);
        palette10.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush6);
        TakeButton->setPalette(palette10);
        TakeButton->setFont(font2);
        ItemBox = new QComboBox(centralwidget);
        ItemBox->setObjectName(QString::fromUtf8("ItemBox"));
        ItemBox->setGeometry(QRect(750, 310, 131, 25));
        QPalette palette11;
        palette11.setBrush(QPalette::Active, QPalette::WindowText, brush6);
        palette11.setBrush(QPalette::Active, QPalette::Button, brush53);
        palette11.setBrush(QPalette::Active, QPalette::Light, brush54);
        palette11.setBrush(QPalette::Active, QPalette::Midlight, brush55);
        palette11.setBrush(QPalette::Active, QPalette::Dark, brush56);
        palette11.setBrush(QPalette::Active, QPalette::Mid, brush57);
        palette11.setBrush(QPalette::Active, QPalette::Text, brush6);
        palette11.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette11.setBrush(QPalette::Active, QPalette::ButtonText, brush6);
        palette11.setBrush(QPalette::Active, QPalette::Base, brush);
        palette11.setBrush(QPalette::Active, QPalette::Window, brush53);
        palette11.setBrush(QPalette::Active, QPalette::Shadow, brush6);
        palette11.setBrush(QPalette::Active, QPalette::AlternateBase, brush58);
        palette11.setBrush(QPalette::Active, QPalette::ToolTipBase, brush7);
        palette11.setBrush(QPalette::Active, QPalette::ToolTipText, brush6);
        palette11.setBrush(QPalette::Inactive, QPalette::WindowText, brush6);
        palette11.setBrush(QPalette::Inactive, QPalette::Button, brush8);
        palette11.setBrush(QPalette::Inactive, QPalette::Light, brush);
        palette11.setBrush(QPalette::Inactive, QPalette::Midlight, brush9);
        palette11.setBrush(QPalette::Inactive, QPalette::Dark, brush10);
        palette11.setBrush(QPalette::Inactive, QPalette::Mid, brush11);
        palette11.setBrush(QPalette::Inactive, QPalette::Text, brush6);
        palette11.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette11.setBrush(QPalette::Inactive, QPalette::ButtonText, brush6);
        palette11.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette11.setBrush(QPalette::Inactive, QPalette::Window, brush8);
        palette11.setBrush(QPalette::Inactive, QPalette::Shadow, brush12);
        palette11.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush13);
        palette11.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush7);
        palette11.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush6);
        palette11.setBrush(QPalette::Disabled, QPalette::WindowText, brush56);
        palette11.setBrush(QPalette::Disabled, QPalette::Button, brush53);
        palette11.setBrush(QPalette::Disabled, QPalette::Light, brush54);
        palette11.setBrush(QPalette::Disabled, QPalette::Midlight, brush55);
        palette11.setBrush(QPalette::Disabled, QPalette::Dark, brush56);
        palette11.setBrush(QPalette::Disabled, QPalette::Mid, brush57);
        palette11.setBrush(QPalette::Disabled, QPalette::Text, brush56);
        palette11.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette11.setBrush(QPalette::Disabled, QPalette::ButtonText, brush56);
        palette11.setBrush(QPalette::Disabled, QPalette::Base, brush53);
        palette11.setBrush(QPalette::Disabled, QPalette::Window, brush53);
        palette11.setBrush(QPalette::Disabled, QPalette::Shadow, brush14);
        palette11.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush13);
        palette11.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush7);
        palette11.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush6);
        ItemBox->setPalette(palette11);
        inventorycounter = new QLCDNumber(centralwidget);
        inventorycounter->setObjectName(QString::fromUtf8("inventorycounter"));
        inventorycounter->setGeometry(QRect(1170, 440, 51, 21));
        QPalette palette12;
        palette12.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette12.setBrush(QPalette::Active, QPalette::Button, brush);
        palette12.setBrush(QPalette::Active, QPalette::Light, brush);
        QBrush brush59(QColor(238, 238, 236, 255));
        brush59.setStyle(Qt::SolidPattern);
        palette12.setBrush(QPalette::Active, QPalette::Midlight, brush59);
        palette12.setBrush(QPalette::Active, QPalette::Dark, brush);
        palette12.setBrush(QPalette::Active, QPalette::Mid, brush);
        palette12.setBrush(QPalette::Active, QPalette::Text, brush);
        palette12.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette12.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette12.setBrush(QPalette::Active, QPalette::Base, brush);
        palette12.setBrush(QPalette::Active, QPalette::Window, brush6);
        palette12.setBrush(QPalette::Active, QPalette::Shadow, brush6);
        palette12.setBrush(QPalette::Active, QPalette::Highlight, brush39);
        palette12.setBrush(QPalette::Active, QPalette::HighlightedText, brush);
        palette12.setBrush(QPalette::Active, QPalette::Link, brush40);
        palette12.setBrush(QPalette::Active, QPalette::LinkVisited, brush41);
        palette12.setBrush(QPalette::Active, QPalette::AlternateBase, brush6);
        palette12.setBrush(QPalette::Active, QPalette::NoRole, brush6);
        palette12.setBrush(QPalette::Active, QPalette::ToolTipBase, brush7);
        palette12.setBrush(QPalette::Active, QPalette::ToolTipText, brush6);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette12.setBrush(QPalette::Active, QPalette::PlaceholderText, brush42);
#endif
        palette12.setBrush(QPalette::Inactive, QPalette::WindowText, brush6);
        palette12.setBrush(QPalette::Inactive, QPalette::Button, brush8);
        palette12.setBrush(QPalette::Inactive, QPalette::Light, brush);
        palette12.setBrush(QPalette::Inactive, QPalette::Midlight, brush9);
        palette12.setBrush(QPalette::Inactive, QPalette::Dark, brush10);
        palette12.setBrush(QPalette::Inactive, QPalette::Mid, brush11);
        palette12.setBrush(QPalette::Inactive, QPalette::Text, brush6);
        palette12.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette12.setBrush(QPalette::Inactive, QPalette::ButtonText, brush6);
        palette12.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette12.setBrush(QPalette::Inactive, QPalette::Window, brush8);
        palette12.setBrush(QPalette::Inactive, QPalette::Shadow, brush12);
        palette12.setBrush(QPalette::Inactive, QPalette::Highlight, brush39);
        palette12.setBrush(QPalette::Inactive, QPalette::HighlightedText, brush);
        palette12.setBrush(QPalette::Inactive, QPalette::Link, brush40);
        palette12.setBrush(QPalette::Inactive, QPalette::LinkVisited, brush41);
        palette12.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush13);
        QBrush brush60(QColor(0, 0, 0, 255));
        brush60.setStyle(Qt::NoBrush);
        palette12.setBrush(QPalette::Inactive, QPalette::NoRole, brush60);
        palette12.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush7);
        palette12.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush6);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette12.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush42);
#endif
        palette12.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        palette12.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette12.setBrush(QPalette::Disabled, QPalette::Light, brush);
        palette12.setBrush(QPalette::Disabled, QPalette::Midlight, brush59);
        palette12.setBrush(QPalette::Disabled, QPalette::Dark, brush);
        palette12.setBrush(QPalette::Disabled, QPalette::Mid, brush);
        palette12.setBrush(QPalette::Disabled, QPalette::Text, brush);
        palette12.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette12.setBrush(QPalette::Disabled, QPalette::ButtonText, brush);
        palette12.setBrush(QPalette::Disabled, QPalette::Base, brush6);
        palette12.setBrush(QPalette::Disabled, QPalette::Window, brush6);
        palette12.setBrush(QPalette::Disabled, QPalette::Shadow, brush14);
        palette12.setBrush(QPalette::Disabled, QPalette::Highlight, brush45);
        palette12.setBrush(QPalette::Disabled, QPalette::HighlightedText, brush);
        palette12.setBrush(QPalette::Disabled, QPalette::Link, brush40);
        palette12.setBrush(QPalette::Disabled, QPalette::LinkVisited, brush41);
        palette12.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush13);
        QBrush brush61(QColor(0, 0, 0, 255));
        brush61.setStyle(Qt::NoBrush);
        palette12.setBrush(QPalette::Disabled, QPalette::NoRole, brush61);
        palette12.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush7);
        palette12.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush6);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette12.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush42);
#endif
        inventorycounter->setPalette(palette12);
        inventory_label = new QLabel(centralwidget);
        inventory_label->setObjectName(QString::fromUtf8("inventory_label"));
        inventory_label->setGeometry(QRect(880, 390, 131, 41));
        QFont font3;
        font3.setBold(true);
        font3.setUnderline(true);
        inventory_label->setFont(font3);
        inventory_label->setFrameShape(QFrame::NoFrame);
        inventory_label->setLineWidth(2);
        inventory_label->setTextFormat(Qt::AutoText);
        inventory_label->setScaledContents(false);
        inventory_label->setAlignment(Qt::AlignCenter);
        InventoryBox = new QComboBox(centralwidget);
        InventoryBox->setObjectName(QString::fromUtf8("InventoryBox"));
        InventoryBox->setGeometry(QRect(740, 440, 421, 25));
        QPalette palette13;
        palette13.setBrush(QPalette::Active, QPalette::WindowText, brush6);
        palette13.setBrush(QPalette::Active, QPalette::Button, brush47);
        palette13.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette13.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        palette13.setBrush(QPalette::Active, QPalette::Dark, brush4);
        palette13.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette13.setBrush(QPalette::Active, QPalette::Text, brush6);
        palette13.setBrush(QPalette::Active, QPalette::BrightText, brush6);
        palette13.setBrush(QPalette::Active, QPalette::ButtonText, brush6);
        palette13.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette13.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette13.setBrush(QPalette::Active, QPalette::Shadow, brush6);
        palette13.setBrush(QPalette::Active, QPalette::Highlight, brush39);
        palette13.setBrush(QPalette::Active, QPalette::HighlightedText, brush);
        palette13.setBrush(QPalette::Active, QPalette::Link, brush40);
        palette13.setBrush(QPalette::Active, QPalette::LinkVisited, brush41);
        palette13.setBrush(QPalette::Active, QPalette::AlternateBase, brush4);
        QBrush brush62(QColor(0, 0, 0, 255));
        brush62.setStyle(Qt::NoBrush);
        palette13.setBrush(QPalette::Active, QPalette::NoRole, brush62);
        palette13.setBrush(QPalette::Active, QPalette::ToolTipBase, brush7);
        palette13.setBrush(QPalette::Active, QPalette::ToolTipText, brush6);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette13.setBrush(QPalette::Active, QPalette::PlaceholderText, brush42);
#endif
        palette13.setBrush(QPalette::Inactive, QPalette::WindowText, brush6);
        palette13.setBrush(QPalette::Inactive, QPalette::Button, brush8);
        palette13.setBrush(QPalette::Inactive, QPalette::Light, brush);
        palette13.setBrush(QPalette::Inactive, QPalette::Midlight, brush9);
        palette13.setBrush(QPalette::Inactive, QPalette::Dark, brush10);
        palette13.setBrush(QPalette::Inactive, QPalette::Mid, brush11);
        palette13.setBrush(QPalette::Inactive, QPalette::Text, brush6);
        palette13.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette13.setBrush(QPalette::Inactive, QPalette::ButtonText, brush6);
        palette13.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette13.setBrush(QPalette::Inactive, QPalette::Window, brush8);
        palette13.setBrush(QPalette::Inactive, QPalette::Shadow, brush12);
        palette13.setBrush(QPalette::Inactive, QPalette::Highlight, brush39);
        palette13.setBrush(QPalette::Inactive, QPalette::HighlightedText, brush);
        palette13.setBrush(QPalette::Inactive, QPalette::Link, brush40);
        palette13.setBrush(QPalette::Inactive, QPalette::LinkVisited, brush41);
        palette13.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush13);
        QBrush brush63(QColor(0, 0, 0, 255));
        brush63.setStyle(Qt::NoBrush);
        palette13.setBrush(QPalette::Inactive, QPalette::NoRole, brush63);
        palette13.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush7);
        palette13.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush6);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette13.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush42);
#endif
        palette13.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette13.setBrush(QPalette::Disabled, QPalette::Button, brush47);
        palette13.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette13.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette13.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette13.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette13.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette13.setBrush(QPalette::Disabled, QPalette::BrightText, brush6);
        palette13.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette13.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette13.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette13.setBrush(QPalette::Disabled, QPalette::Shadow, brush14);
        palette13.setBrush(QPalette::Disabled, QPalette::Highlight, brush45);
        palette13.setBrush(QPalette::Disabled, QPalette::HighlightedText, brush);
        palette13.setBrush(QPalette::Disabled, QPalette::Link, brush40);
        palette13.setBrush(QPalette::Disabled, QPalette::LinkVisited, brush41);
        palette13.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush13);
        QBrush brush64(QColor(0, 0, 0, 255));
        brush64.setStyle(Qt::NoBrush);
        palette13.setBrush(QPalette::Disabled, QPalette::NoRole, brush64);
        palette13.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush7);
        palette13.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush6);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette13.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush42);
#endif
        InventoryBox->setPalette(palette13);
        DropButton = new QPushButton(centralwidget);
        DropButton->setObjectName(QString::fromUtf8("DropButton"));
        DropButton->setGeometry(QRect(1030, 250, 131, 61));
        QPalette palette14;
        palette14.setBrush(QPalette::Active, QPalette::WindowText, brush6);
        palette14.setBrush(QPalette::Active, QPalette::Button, brush47);
        palette14.setBrush(QPalette::Active, QPalette::Light, brush);
        palette14.setBrush(QPalette::Active, QPalette::Midlight, brush48);
        palette14.setBrush(QPalette::Active, QPalette::Dark, brush49);
        palette14.setBrush(QPalette::Active, QPalette::Mid, brush50);
        palette14.setBrush(QPalette::Active, QPalette::Text, brush6);
        palette14.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette14.setBrush(QPalette::Active, QPalette::ButtonText, brush6);
        palette14.setBrush(QPalette::Active, QPalette::Base, brush);
        palette14.setBrush(QPalette::Active, QPalette::Window, brush47);
        palette14.setBrush(QPalette::Active, QPalette::Shadow, brush6);
        palette14.setBrush(QPalette::Active, QPalette::AlternateBase, brush48);
        palette14.setBrush(QPalette::Active, QPalette::ToolTipBase, brush7);
        palette14.setBrush(QPalette::Active, QPalette::ToolTipText, brush6);
        palette14.setBrush(QPalette::Inactive, QPalette::WindowText, brush6);
        palette14.setBrush(QPalette::Inactive, QPalette::Button, brush8);
        palette14.setBrush(QPalette::Inactive, QPalette::Light, brush);
        palette14.setBrush(QPalette::Inactive, QPalette::Midlight, brush9);
        palette14.setBrush(QPalette::Inactive, QPalette::Dark, brush10);
        palette14.setBrush(QPalette::Inactive, QPalette::Mid, brush11);
        palette14.setBrush(QPalette::Inactive, QPalette::Text, brush6);
        palette14.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette14.setBrush(QPalette::Inactive, QPalette::ButtonText, brush6);
        palette14.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette14.setBrush(QPalette::Inactive, QPalette::Window, brush8);
        palette14.setBrush(QPalette::Inactive, QPalette::Shadow, brush12);
        palette14.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush13);
        palette14.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush7);
        palette14.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush6);
        palette14.setBrush(QPalette::Disabled, QPalette::WindowText, brush49);
        palette14.setBrush(QPalette::Disabled, QPalette::Button, brush47);
        palette14.setBrush(QPalette::Disabled, QPalette::Light, brush);
        palette14.setBrush(QPalette::Disabled, QPalette::Midlight, brush48);
        palette14.setBrush(QPalette::Disabled, QPalette::Dark, brush49);
        palette14.setBrush(QPalette::Disabled, QPalette::Mid, brush50);
        palette14.setBrush(QPalette::Disabled, QPalette::Text, brush49);
        palette14.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette14.setBrush(QPalette::Disabled, QPalette::ButtonText, brush49);
        palette14.setBrush(QPalette::Disabled, QPalette::Base, brush47);
        palette14.setBrush(QPalette::Disabled, QPalette::Window, brush47);
        palette14.setBrush(QPalette::Disabled, QPalette::Shadow, brush14);
        palette14.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush13);
        palette14.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush7);
        palette14.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush6);
        DropButton->setPalette(palette14);
        DropButton->setFont(font2);
        wordleEdit = new QLineEdit(centralwidget);
        wordleEdit->setObjectName(QString::fromUtf8("wordleEdit"));
        wordleEdit->setGeometry(QRect(260, 540, 111, 25));
        QPalette palette15;
        palette15.setBrush(QPalette::Active, QPalette::WindowText, brush6);
        palette15.setBrush(QPalette::Active, QPalette::Button, brush47);
        palette15.setBrush(QPalette::Active, QPalette::Light, brush);
        palette15.setBrush(QPalette::Active, QPalette::Midlight, brush48);
        palette15.setBrush(QPalette::Active, QPalette::Dark, brush49);
        palette15.setBrush(QPalette::Active, QPalette::Mid, brush50);
        palette15.setBrush(QPalette::Active, QPalette::Text, brush6);
        palette15.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette15.setBrush(QPalette::Active, QPalette::ButtonText, brush6);
        palette15.setBrush(QPalette::Active, QPalette::Base, brush47);
        palette15.setBrush(QPalette::Active, QPalette::Window, brush47);
        palette15.setBrush(QPalette::Active, QPalette::Shadow, brush6);
        palette15.setBrush(QPalette::Active, QPalette::Highlight, brush39);
        palette15.setBrush(QPalette::Active, QPalette::HighlightedText, brush);
        palette15.setBrush(QPalette::Active, QPalette::Link, brush40);
        palette15.setBrush(QPalette::Active, QPalette::LinkVisited, brush41);
        palette15.setBrush(QPalette::Active, QPalette::AlternateBase, brush48);
        palette15.setBrush(QPalette::Active, QPalette::NoRole, brush6);
        palette15.setBrush(QPalette::Active, QPalette::ToolTipBase, brush7);
        palette15.setBrush(QPalette::Active, QPalette::ToolTipText, brush6);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette15.setBrush(QPalette::Active, QPalette::PlaceholderText, brush42);
#endif
        palette15.setBrush(QPalette::Inactive, QPalette::WindowText, brush6);
        palette15.setBrush(QPalette::Inactive, QPalette::Button, brush8);
        palette15.setBrush(QPalette::Inactive, QPalette::Light, brush);
        palette15.setBrush(QPalette::Inactive, QPalette::Midlight, brush9);
        palette15.setBrush(QPalette::Inactive, QPalette::Dark, brush10);
        palette15.setBrush(QPalette::Inactive, QPalette::Mid, brush11);
        palette15.setBrush(QPalette::Inactive, QPalette::Text, brush6);
        palette15.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette15.setBrush(QPalette::Inactive, QPalette::ButtonText, brush6);
        palette15.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette15.setBrush(QPalette::Inactive, QPalette::Window, brush8);
        palette15.setBrush(QPalette::Inactive, QPalette::Shadow, brush12);
        palette15.setBrush(QPalette::Inactive, QPalette::Highlight, brush39);
        palette15.setBrush(QPalette::Inactive, QPalette::HighlightedText, brush);
        palette15.setBrush(QPalette::Inactive, QPalette::Link, brush40);
        palette15.setBrush(QPalette::Inactive, QPalette::LinkVisited, brush41);
        palette15.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush13);
        QBrush brush65(QColor(0, 0, 0, 255));
        brush65.setStyle(Qt::NoBrush);
        palette15.setBrush(QPalette::Inactive, QPalette::NoRole, brush65);
        palette15.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush7);
        palette15.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush6);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette15.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush42);
#endif
        palette15.setBrush(QPalette::Disabled, QPalette::WindowText, brush49);
        palette15.setBrush(QPalette::Disabled, QPalette::Button, brush47);
        palette15.setBrush(QPalette::Disabled, QPalette::Light, brush);
        palette15.setBrush(QPalette::Disabled, QPalette::Midlight, brush48);
        palette15.setBrush(QPalette::Disabled, QPalette::Dark, brush49);
        palette15.setBrush(QPalette::Disabled, QPalette::Mid, brush50);
        palette15.setBrush(QPalette::Disabled, QPalette::Text, brush49);
        palette15.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette15.setBrush(QPalette::Disabled, QPalette::ButtonText, brush49);
        palette15.setBrush(QPalette::Disabled, QPalette::Base, brush47);
        palette15.setBrush(QPalette::Disabled, QPalette::Window, brush47);
        palette15.setBrush(QPalette::Disabled, QPalette::Shadow, brush14);
        palette15.setBrush(QPalette::Disabled, QPalette::Highlight, brush45);
        palette15.setBrush(QPalette::Disabled, QPalette::HighlightedText, brush);
        palette15.setBrush(QPalette::Disabled, QPalette::Link, brush40);
        palette15.setBrush(QPalette::Disabled, QPalette::LinkVisited, brush41);
        palette15.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush13);
        QBrush brush66(QColor(0, 0, 0, 255));
        brush66.setStyle(Qt::NoBrush);
        palette15.setBrush(QPalette::Disabled, QPalette::NoRole, brush66);
        palette15.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush7);
        palette15.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush6);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette15.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush42);
#endif
        wordleEdit->setPalette(palette15);
        wordleEdit->setFrame(true);
        wordleEdit->setAlignment(Qt::AlignCenter);
        WordleInputLabel = new QLabel(centralwidget);
        WordleInputLabel->setObjectName(QString::fromUtf8("WordleInputLabel"));
        WordleInputLabel->setGeometry(QRect(270, 520, 91, 17));
        WordleInputLabel->setFont(font3);
        AttackButton = new QPushButton(centralwidget);
        AttackButton->setObjectName(QString::fromUtf8("AttackButton"));
        AttackButton->setGeometry(QRect(1030, 30, 131, 61));
        QPalette palette16;
        palette16.setBrush(QPalette::Active, QPalette::WindowText, brush6);
        palette16.setBrush(QPalette::Active, QPalette::Button, brush47);
        palette16.setBrush(QPalette::Active, QPalette::Light, brush);
        palette16.setBrush(QPalette::Active, QPalette::Midlight, brush48);
        palette16.setBrush(QPalette::Active, QPalette::Dark, brush49);
        palette16.setBrush(QPalette::Active, QPalette::Mid, brush50);
        palette16.setBrush(QPalette::Active, QPalette::Text, brush6);
        palette16.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette16.setBrush(QPalette::Active, QPalette::ButtonText, brush6);
        palette16.setBrush(QPalette::Active, QPalette::Base, brush);
        palette16.setBrush(QPalette::Active, QPalette::Window, brush47);
        palette16.setBrush(QPalette::Active, QPalette::Shadow, brush6);
        palette16.setBrush(QPalette::Active, QPalette::AlternateBase, brush48);
        palette16.setBrush(QPalette::Active, QPalette::ToolTipBase, brush7);
        palette16.setBrush(QPalette::Active, QPalette::ToolTipText, brush6);
        palette16.setBrush(QPalette::Inactive, QPalette::WindowText, brush6);
        palette16.setBrush(QPalette::Inactive, QPalette::Button, brush8);
        palette16.setBrush(QPalette::Inactive, QPalette::Light, brush);
        palette16.setBrush(QPalette::Inactive, QPalette::Midlight, brush9);
        palette16.setBrush(QPalette::Inactive, QPalette::Dark, brush10);
        palette16.setBrush(QPalette::Inactive, QPalette::Mid, brush11);
        palette16.setBrush(QPalette::Inactive, QPalette::Text, brush6);
        palette16.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette16.setBrush(QPalette::Inactive, QPalette::ButtonText, brush6);
        palette16.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette16.setBrush(QPalette::Inactive, QPalette::Window, brush8);
        palette16.setBrush(QPalette::Inactive, QPalette::Shadow, brush12);
        palette16.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush13);
        palette16.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush7);
        palette16.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush6);
        palette16.setBrush(QPalette::Disabled, QPalette::WindowText, brush49);
        palette16.setBrush(QPalette::Disabled, QPalette::Button, brush47);
        palette16.setBrush(QPalette::Disabled, QPalette::Light, brush);
        palette16.setBrush(QPalette::Disabled, QPalette::Midlight, brush48);
        palette16.setBrush(QPalette::Disabled, QPalette::Dark, brush49);
        palette16.setBrush(QPalette::Disabled, QPalette::Mid, brush50);
        palette16.setBrush(QPalette::Disabled, QPalette::Text, brush49);
        palette16.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette16.setBrush(QPalette::Disabled, QPalette::ButtonText, brush49);
        palette16.setBrush(QPalette::Disabled, QPalette::Base, brush47);
        palette16.setBrush(QPalette::Disabled, QPalette::Window, brush47);
        palette16.setBrush(QPalette::Disabled, QPalette::Shadow, brush14);
        palette16.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush13);
        palette16.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush7);
        palette16.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush6);
        AttackButton->setPalette(palette16);
        AttackButton->setFont(font2);
        MainWindow->setCentralWidget(centralwidget);
        menubar = new QMenuBar(MainWindow);
        menubar->setObjectName(QString::fromUtf8("menubar"));
        menubar->setGeometry(QRect(0, 0, 1272, 22));
        MainWindow->setMenuBar(menubar);
        statusbar = new QStatusBar(MainWindow);
        statusbar->setObjectName(QString::fromUtf8("statusbar"));
        MainWindow->setStatusBar(statusbar);

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QCoreApplication::translate("MainWindow", "MainWindow", nullptr));
        NorthButton->setText(QCoreApplication::translate("MainWindow", "North", nullptr));
        EastButton->setText(QCoreApplication::translate("MainWindow", "East", nullptr));
        WestButton->setText(QCoreApplication::translate("MainWindow", "West", nullptr));
        SouthButton->setText(QCoreApplication::translate("MainWindow", "South", nullptr));
        dir_label->setText(QCoreApplication::translate("MainWindow", "Location", nullptr));
        MapButton->setText(QCoreApplication::translate("MainWindow", "Map", nullptr));
        imgLabel->setText(QString());
        TeleportButton->setText(QCoreApplication::translate("MainWindow", "Teleport", nullptr));
        TakeButton->setText(QCoreApplication::translate("MainWindow", "Take Item", nullptr));
        inventory_label->setText(QCoreApplication::translate("MainWindow", "Inventory", nullptr));
        DropButton->setText(QCoreApplication::translate("MainWindow", "Drop Item", nullptr));
        wordleEdit->setText(QString());
        WordleInputLabel->setText(QCoreApplication::translate("MainWindow", "Puzzle Input", nullptr));
        AttackButton->setText(QCoreApplication::translate("MainWindow", "Attack", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
